### ISSUE TITLE
 Extra inputs are not permitted

### ISSUE THREAD

**Issue by whatever193** [shamhi/TapSwapBot#1]
(venv) C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main>py main.py
Traceback (most recent call last):
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\bot\utils\launcher.py", line 8, in <module>
    from bot.config import settings
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\bot\config\config.py", line 27, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
random_clicks_count
  Extra inputs are not permitted [type=extra_forbidden, input_value='[1, 15]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden

(venv) C:\Users\accli\Downloads\TapSwapBot-main\TapSwapBot-main> 
I try value like [1, 50] but i cant run this scrips

**Comment by shamhi** [comment]
try 1,50 without staples

**Comment by whatever193** [comment]
> try 1,50 without staples

Thank you. I fixed it fill it like this for other people "list[int] = [50, 200]"
