### ISSUE TITLE
Big Error

### ISSUE THREAD

**Issue by Selin2005** [shamhi/TapSwapBot#101]
`Traceback (most recent call last):
  File "/home/helpaipr/Coins2/public/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/helpaipr/Coins2/public/TapSwapBot/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/helpaipr/Coins2/public/venv/lib64/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/helpaipr/Coins2/public/venv/lib64/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/helpaipr/Coins2/public/venv/lib64/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/helpaipr/Coins2/public/venv/lib64/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/helpaipr/Coins2/public/venv/lib64/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

2024-06-20 14:11:30 | ERROR    | 126 - h3 | Unknown error while getting Access Token: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
 | Response text: {"chq":"fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbde4a0c6baf3e9e4aff3c7d6ade8faebf1eeeac9abbab1baf0e9d6c4f3f9f0a9f2e8efd0dfd0fbc9decabab1baf3f9f0acf3c7f7acefaccdcce9fad6bab1baf3f9f0acebfad9dcdfd0efabbab1baf0c7f0a8f0f9f4c5f0f8c5e9ece8f7d5eaecbab1baf0d7fba8dfd6a8f9e8e5debab1baf0d7d6acf3c7e4caf2f8effee8e8efafe8cabab1baf0c7dacaf3adc9e9ded6e7abebcabab1baf0e9ecc4f2e9ff`

**Comment by CruistCoder** [comment]
The error is being corrected

**Comment by Gruvikus** [comment]
Не работает...
