### ISSUE TITLE
After the Fix CV update the problem is still remain

### ISSUE THREAD

**Issue by ZeroParadoxHome** [shamhi/TapSwapBot#102]
2024-06-20 12:21:39 | ERROR    | 391 - X | Unknown error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/root/TapSwapBot/bot/core/tapper.py", line 117, in login
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-20 12:21:40 | ERROR    | 126 - X | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
2024-06-20 12:21:40 | INFO     | 164 - All sessions are closed. Quitting driver...

**Comment by CruistCoder** [comment]
Please fix

**Comment by majestixxxx** [comment]
pls fix

**Comment by ButCheR-PRO** [comment]
Dupe
1. https://github.com/shamhi/TapSwapBot/issues/112
