### ISSUE TITLE
Очень сильно спамит ошибками. Не работает.

### ISSUE THREAD

**Issue by Newfpv** [shamhi/TapSwapBot#103]
Очень сильно спамит ошибками. Не работает.

> ```cmd
> Attaching to tapswap
> tapswap  | 2024-06-20 13:06:37 | INFO     | 51 - Downloading webdriver. It may take some time...
> tapswap  | 2024-06-20 13:06:38 | INFO     | 55 - Webdriver downloaded successfully
> tapswap  | 2024-06-20 13:06:38 | INFO     | 79 - Detected 6 sessions | 3 proxies
> tapswap  | 2024-06-20 13:06:39 | INFO     | 204 - pavelsys | Proxy IP: 46.232.94.125
> tapswap  | 2024-06-20 13:06:40 | INFO     | 204 - NewFPV_PR | Proxy IP: 95.164.111.108
> tapswap  | 2024-06-20 13:06:40 | INFO     | 204 - Pavel | Proxy IP: 154.194.119.201
> tapswap  | 2024-06-20 13:06:40 | INFO     | 204 - pseudoh1 Artur | Proxy IP: 95.164.111.108
> tapswap  | 2024-06-20 13:06:40 | INFO     | 204 - newfpv | Proxy IP: 46.232.94.125
> tapswap  | 2024-06-20 13:06:40 | INFO     | 204 - WiseAI | Proxy IP: 154.194.119.201
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:48 | ERROR    | 126 - Pavel | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:48 | ERROR    | 126 - newfpv | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:49 | ERROR    | 126 - pavelsys | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:49 | ERROR    | 126 - WiseAI | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:50 | ERROR    | 126 - pseudoh1 Artur | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:06:50 | INFO     | 164 - All sessions are closed. Quitting driver...
> ^[[23~tapswap  | 2024-06-20 13:06:52 | ERROR    | 391 - Pavel | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:06:52 | ERROR    | 391 - newfpv | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:06:52 | ERROR    | 391 - pavelsys | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:06:52 | ERROR    | 391 - WiseAI | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:06:53 | ERROR    | 126 - NewFPV_PR | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:06:53 | ERROR    | 391 - pseudoh1 Artur | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:02 | ERROR    | 391 - NewFPV_PR | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:02 | ERROR    | 126 - Pavel | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:02 | ERROR    | 126 - WiseAI | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:02 | ERROR    | 126 - pavelsys | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:03 | ERROR    | 126 - newfpv | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:03 | ERROR    | 126 - pseudoh1 Artur | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:05 | INFO     | 164 - All sessions are closed. Quitting driver...
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 391 - Pavel | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 391 - WiseAI | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 391 - pavelsys | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 391 - newfpv | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 391 - pseudoh1 Artur | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:06 | ERROR    | 126 - NewFPV_PR | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:09 | ERROR    | 391 - NewFPV_PR | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:15 | ERROR    | 126 - pseudoh1 Artur | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:15 | ERROR    | 126 - WiseAI | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:15 | ERROR    | 126 - Pavel | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:16 | ERROR    | 126 - pavelsys | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:16 | ERROR    | 126 - newfpv | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:16 | INFO     | 164 - All sessions are closed. Quitting driver...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:18 | ERROR    | 126 - NewFPV_PR | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:18 | ERROR    | 391 - pseudoh1 Artur | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:18 | ERROR    | 391 - WiseAI | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:18 | ERROR    | 391 - Pavel | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:19 | ERROR    | 391 - pavelsys | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:19 | ERROR    | 391 - newfpv | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:21 | ERROR    | 391 - NewFPV_PR | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:27 | ERROR    | 126 - pseudoh1 Artur | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:28 | ERROR    | 126 - NewFPV_PR | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:28 | ERROR    | 126 - Pavel | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:28 | ERROR    | 126 - pavelsys | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:29 | ERROR    | 126 - WiseAI | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:29 | INFO     | 164 - All sessions are closed. Quitting driver...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:30 | ERROR    | 126 - newfpv | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:30 | ERROR    | 391 - pseudoh1 Artur | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:31 | ERROR    | 391 - NewFPV_PR | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:31 | ERROR    | 391 - Pavel | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:31 | ERROR    | 391 - pavelsys | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:32 | ERROR    | 391 - WiseAI | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:33 | ERROR    | 391 - newfpv | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:39 | ERROR    | 126 - pseudoh1 Artur | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:40 | ERROR    | 126 - NewFPV_PR | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:40 | ERROR    | 126 - Pavel | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:40 | ERROR    | 126 - pavelsys | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:40 | ERROR    | 126 - WiseAI | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:40 | INFO     | 164 - All sessions are closed. Quitting driver...
> tapswap  | Traceback (most recent call last):
> tapswap  |   File "/app/bot/core/tapper.py", line 117, in login
> tapswap  |     response.raise_for_status()
> tapswap  |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
> tapswap  |     raise ClientResponseError(
> tapswap  | aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
> tapswap  | 2024-06-20 13:07:42 | ERROR    | 126 - newfpv | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
> tapswap  | 2024-06-20 13:07:42 | ERROR    | 391 - pseudoh1 Artur | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:43 | ERROR    | 391 - NewFPV_PR | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:43 | ERROR    | 391 - Pavel | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:43 | ERROR    | 391 - pavelsys | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:43 | ERROR    | 391 - WiseAI | Unknown error: cannot unpack non-iterable NoneType object
> tapswap  | 2024-06-20 13:07:45 | ERROR    | 391 - newfpv | Unknown error: cannot unpack non-iterable NoneType object
> ```

**Comment by mrdarkerr** [comment]
same

**Comment by tegast** [comment]
и чо не нашли решение?

**Comment by Newfpv** [comment]
Обновили тапсвап. Ещё не проверял

**Comment by ButCheR-PRO** [comment]
Пока ждём фикс
1. https://github.com/shamhi/TapSwapBot/issues/112
