### ISSUE TITLE
Same Error After Update 

### ISSUE THREAD

**Issue by Pawansingh333** [shamhi/TapSwapBot#106]
http.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-20 20:11:03 | ERROR    | 126 - 91xxxxxxxxxxx | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
2024-06-20 20:11:03 | ERROR    | 391 - 91xxxxxxxxxx | Unknown error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\pixelversexyzbot-main\TapSwapBot-main (1)\TapSwapBot-main\bot\core\tapper.py", line 117, in login
    response.raise_for_status()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-20 20:11:04 | ERROR    | 126 - 916026844662 | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}..

**Comment by m-a-prod** [comment]
++

**Comment by Dumpff** [comment]
++

**Comment by CruistCoder** [comment]
same

**Comment by Visualua** [comment]
В Пулах есть решение этой проблемы [https://github.com/shamhi/TapSwapBot/pull/107](https://github.com/shamhi/TapSwapBot/pull/107)

**Comment by enolife** [comment]
> В Пулах есть решение этой проблемы #107

Work perfectly

**Comment by phillipssa** [comment]
after applied #107, it have another issue such as below 
"Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "D:\usb\tabtap\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\usb\tabtap\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\usb\tabtap\TapSwapBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "D:\usb\tabtap\TapSwapBot\bot\core\tapper.py", line 17, in <module>
    from bot.utils.scripts import extract_chq, escape_html
  File "D:\usb\tabtap\TapSwapBot\bot\utils\scripts.py", line 145
    driver.execute_script("""
IndentationError: unexpected indent
Press any key to continue . . ." . Pls help

**Comment by Visualua** [comment]
> http.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') 2024-06-20 20:11:03 | ERROR | 126 - 91xxxxxxxxxxx | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}... 2024-06-20 20:11:03 | ERROR | 391 - 91xxxxxxxxxx | Unknown error: cannot unpack non-iterable NoneType object Traceback (most recent call last): File "C:\Users\abc\Desktop\pixelversexyzbot-main\TapSwapBot-main (1)\TapSwapBot-main\bot\core\tapper.py", line 117, in login response.raise_for_status() File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') 2024-06-20 20:11:04 | ERROR | 126 - 916026844662 | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_chr[2]"}..

replace the lines carefully. you made a mistake when replacing, you are informed about it in scripts.py on line 145

**Comment by m-a-prod** [comment]
update code from repo, it works fine =)

**Comment by ButCheR-PRO** [comment]
> #107 fixes the problem.

Fix does not work :(
Same error, 
1. https://github.com/shamhi/TapSwapBot/issues/112
