### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Dandeib** [shamhi/TapSwapBot#117]
2024-06-22 14:39:22 | INFO     | 51 - Downloading webdriver. It may take some time...
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "powershell" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Traceback (most recent call last):
  File "C:\Users\danie\Desktop\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\danie\Desktop\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\danie\Desktop\TapSwapBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\danie\Desktop\TapSwapBot-main\bot\core\tapper.py", line 17, in <module>
    from bot.utils.scripts import extract_chq, escape_html
  File "C:\Users\danie\Desktop\TapSwapBot-main\bot\utils\scripts.py", line 53, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\Desktop\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\Desktop\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\Desktop\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\Desktop\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\Desktop\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by GravelFire** [comment]
Просто скачиваешь Google Chrome браузер и всё заработает(это самый простой способ)

**Comment by Dandeib** [comment]
> Просто скачиваешь Google Chrome браузер, устанавливаешь на пк и всё заработает(это самый простой способ)
> -
> Работает данный способ на Windows OS

У меня на компьютере установлен Google Chrome
