### ISSUE TITLE
Небольшие проблемы

### ISSUE THREAD

**Issue by AzidKillCam** [shamhi/TapSwapBot#124]
I have this Traceback as output:
Traceback (most recent call last):
  File "C:\Users\Cosmo\Desktop\TapSwapBot-main\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\Cosmo\Desktop\TapSwapBot-main\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\Cosmo\Desktop\TapSwapBot-main\TapSwapBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\Cosmo\Desktop\TapSwapBot-main\TapSwapBot-main\bot\core\tapper.py", line 8, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cosmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

What do I need to do for the code to work correctly?

**Comment by F0RQU1N** [comment]
same shit
