### ISSUE TITLE
Помогите с проблемой.

### ISSUE THREAD

**Issue by MaxZhelt** [shamhi/TapSwapBot#126]
Я уже использую другого бота для HamsterCombat от этого же разработчика. Но вот незадача, у меня никак не получается запустить именно этого бота...

`(venv) C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main>py main.py
2024-06-23 19:21:42 | INFO     | 51 - Downloading webdriver. It may take some time...
Traceback (most recent call last):
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\bot\core\tapper.py", line 17, in <module>
    from bot.utils.scripts import extract_chq, escape_html
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\bot\utils\scripts.py", line 53, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jukma\OneDrive\Рабочий стол\TapSwapBot-main\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
`

У меня вылезает такая ошибка, я уже что только не пробовал, и переустанавливал, и переносил файлы в другое место, ничего не помогает...

Подскажите мне, что я делаю не так.

**Comment by kirajok** [comment]
Установи Google Chrome если не установлен. А вообще бот не работает сейчас
