### ISSUE TITLE
Unknown error while getting Access Token: 400, message='Bad Request', 

### ISSUE THREAD

**Issue by fattahkus** [shamhi/TapSwapBot#127]
Traceback (most recent call last):
  File "d:\python\tapswap\tapswap4\bot\core\tapper.py", line 99, in login
    response.raise_for_status()
  File "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-24 06:52:49 | ERROR    | 129 - username | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_request[3]"}...
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x00000216F9DA6810>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000216F9F74360>, 222315.968)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000216F9DA6850>

**Comment by Mahdikhoubrouy** [comment]
same

**Comment by Pawansingh333** [comment]
no buddy will listen your problem leave and tap manually

**Comment by Artazar13** [comment]
Та же проблема

**Comment by nekooee** [comment]
same

**Comment by efsfssf** [comment]
same

**Comment by Artazar13** [comment]
**Клуб анонимных ботоводов**
Здравствуйте, меня зовут Дмитрий
И у меня тоже забаговал бот TapSwap

**Comment by thanhnguyen92** [comment]
Same issue, but I can play on mobile device.

**Comment by nekooee** [comment]
> Same issue, but I can play on mobile device.

You should send "device is touch" in the header.

> Same issue, but I can play on mobile device.

You should send "touch" in the header.

**Comment by thanhnguyen92** [comment]
> > Same issue, but I can play on mobile device.
> 
> You should send "device is touch" in the header.
> 
> > Same issue, but I can play on mobile device.
> 
> You should send "touch" in the header.

Can you give the example?

**Comment by nekooee** [comment]
> > > Same issue, but I can play on mobile device.
> > 
> > 
> > You should send "device is touch" in the header.
> > > Same issue, but I can play on mobile device.
> > 
> > 
> > You should send "touch" in the header.
> 
> Can you give the example?

in request header add "x-touch" and value "1"
