### ISSUE TITLE
The script does not run

### ISSUE THREAD

**Issue by Mfdrtj** [shamhi/TapSwapBot#15]
(venv) root@ubuntu-2gb-hel1-1:~/TapSwapBot# python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.8/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.8/site-packages/better_proxy/proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
(venv) root@ubuntu-2gb-hel1-1:~/TapSwapBot#

**Comment by shamhi** [comment]
use 3.10 or 3.11
