### ISSUE TITLE
keyerror3

### ISSUE THREAD

**Issue by Kolakpo** [shamhi/TapSwapBot#151]
![Capture d'écran 2024-07-01 192629](https://github.com/shamhi/TapSwapBot/assets/61409188/3ed15f12-0962-4122-bebf-6678b6af7bb3)
help me please
PS C:\Users\HP\Downloads\Compressed\airdrop\TapSwapBot-main> python3 main.py
Traceback (most recent call last):
  File "C:\Users\HP\Downloads\Compressed\airdrop\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\HP\Downloads\Compressed\airdrop\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\HP\Downloads\Compressed\airdrop\TapSwapBot-main\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\HP\Downloads\Compressed\airdrop\TapSwapBot-main\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by Unseable41** [comment]
Have you configured the config.ini file correctly?

**Comment by Kolakpo** [comment]
yes

**Comment by Unseable41** [comment]
try running in a virtual environment with these codes

**Comment by shamhi** [comment]
install python 3.11
