### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrdarkerr** [shamhi/TapSwapBot#153]
```
$python3 main.py ->
2024-07-02 00:15:05 | INFO     | 114 - Downloading webdriver. It may take some time...
/bin/sh: 1: google-chrome: not found
/usr/bin/google-chrome-stable: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
/bin/sh: 1: google-chrome-beta: not found
/bin/sh: 1: google-chrome-dev: not found
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: google-chrome-beta: not found
/bin/sh: 1: google-chrome-dev: not found
/usr/bin/google-chrome-stable: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/root/TapSwapBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "/root/TapSwapBot/bot/core/tapper.py", line 16, in <module>
    from bot.utils.scripts import escape_html, login_in_browser
  File "/root/TapSwapBot/bot/utils/scripts.py", line 116, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/core/driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Unseable41** [comment]
you are getting this error because google chrome is not installed

**Comment by Alexell** [comment]
```
cd TapSwapBot
chmod +x chrome_install.sh
./chrome_install.sh
```
