### ISSUE TITLE
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.

### ISSUE THREAD

**Issue by b0r1sOm4g0** [shamhi/TapSwapBot#156]
I'm trying to run it on Windows 11, Python 3.11 and I get the following error:
![image](https://github.com/shamhi/TapSwapBot/assets/117418584/ab000641-6675-4592-927f-4e34151d63bb)

`BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.
Traceback (most recent call last):
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\b0r1s\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\main.py", line 8, in main
    await process()
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\bot\utils\launcher.py", line 83, in process
    await register_sessions()
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\bot\core\registrator.py", line 26, in register_sessions
    async with session:
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\venv\Lib\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\venv\Lib\site-packages\pyrogram\methods\utilities\start.py", line 62, in start
    await self.authorize()
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\venv\Lib\site-packages\pyrogram\client.py", line 359, in authorize
    sent_code = await self.send_code(self.phone_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\venv\Lib\site-packages\pyrogram\methods\auth\send_code.py", line 79, in send_code
    return types.SentCode._parse(r)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b0r1s\Desktop\Bots\TapSwapBot-shamhi\TapSwapBot\venv\Lib\site-packages\pyrogram\types\authorization\sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
                                 ^^^^^^^^^^^^^^
AttributeError: 'BadMsgNotification' object has no attribute 'type'`

**Comment by VasNick8064** [comment]
Synchronize your time and try using Py3.10
