### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by THMaST3R** [shamhi/TapSwapBot#158]
```
Traceback (most recent call last):
  File "/root/tap/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/tap/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/tap/bot/utils/launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "/root/tap/bot/core/tapper.py", line 16, in <module>
    from bot.utils.scripts import escape_html, login_in_browser
  File "/root/tap/bot/utils/scripts.py", line 116, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
  File "/root/venv/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/root/venv/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "/root/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
  File "/root/venv/lib/python3.10/site-packages/webdriver_manager/core/driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "/root/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
AttributeError: 'NoneType' object has no attribute 'split'
```

what is the problem?

**Comment by ItsAmirAT** [comment]
same issue, did you find any sulotion?

**Comment by ItsAmirAT** [comment]
install chrome on your  server
