### ISSUE TITLE
Downloading web driver error...

### ISSUE THREAD

**Issue by mark522412** [shamhi/TapSwapBot#164]
(venv) C:\bots\tap\TapSwapBot>python main.py
2024-07-08 06:08:33 | INFO     | 114 - Downloading webdriver. It may take some time...
Traceback (most recent call last):
  File "C:\bots\tap\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\bots\tap\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\bots\tap\TapSwapBot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\bots\tap\TapSwapBot\bot\core\tapper.py", line 16, in <module>
    from bot.utils.scripts import escape_html, login_in_browser
  File "C:\bots\tap\TapSwapBot\bot\utils\scripts.py", line 116, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
  File "C:\bots\tap\TapSwapBot\venv\lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\bots\tap\TapSwapBot\venv\lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "C:\bots\tap\TapSwapBot\venv\lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
  File "C:\bots\tap\TapSwapBot\venv\lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "C:\bots\tap\TapSwapBot\venv\lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
AttributeError: 'NoneType' object has no attribute 'split'

(venv) C:\bots\tap\TapSwapBot>

**Comment by EugeneMartein** [comment]
Install Chrome browser on your system.

**Comment by mark522412** [comment]
> Install Chrome browser on your system.

Is this bot still working?

**Comment by EugeneMartein** [comment]
Yes

**Comment by mark522412** [comment]
> Yes

Thank you for the web driver thing. the bot installed now. but new problem :  
2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver...
2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver...
2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver...

someone else said bot url has changed. any idea where to fix this ourselves? looks like the main dev not updating anything at the moment

**Comment by kamranmt21** [comment]
> > Yes
> 
> Thank you for the web driver thing. the bot installed now. but new problem : 2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver... 2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver... 2024-07-18 10:10:14 | INFO | 257 - All sessions are closed. Quitting driver...
> 
> someone else said bot url has changed. any idea where to fix this ourselves? looks like the main dev not updating anything at the moment

now an update is there. it is not working for me yet, but you can try it.

**Comment by mark522412** [comment]
> now an update is there. it is not working for me yet, but you can try it.

Updated the bot. got the same error but it started working after error
