### ISSUE TITLE
Unsupported proxy format

### ISSUE THREAD

**Issue by mrdarkerr** [shamhi/TapSwapBot#177]
```
Traceback (most recent call last):
  File "/root/TapSwapBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/TapSwapBot/main.py", line 8, in main
    await process()
  File "/root/TapSwapBot/bot/utils/launcher.py", line 64, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
  File "/root/TapSwapBot/bot/utils/scripts.py", line 38, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/root/TapSwapBot/bot/utils/scripts.py", line 38, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/better_proxy/proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: 
```

proxies.txt --->>>> 

socks5://7.7.7.7:11758@om:123
socks5://7.7.7.7:15468@om:123
socks5://7.7.7.7:17523@om:123

**I entered my proxies as below, but I get a Unsupported proxy format**

**Comment by mrdarkerr** [comment]
any tip ?

**Comment by mrdarkerr** [comment]
No one is going to help you?
