### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tektungg** [shamhi/TapSwapBot#212]
PS C:\TapSwapBot> python main.py
Traceback (most recent call last):
  File "C:\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\TapSwapBot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\TapSwapBot\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\TapSwapBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
=======================================================================

I just run Install.bat > enter API > run start.bat and this error pops up. what did i miss here?

**Comment by Dener-SBC** [comment]
> # PS C:\TapSwapBot> python main.py
> Traceback (most recent call last):
> File "C:\TapSwapBot\main.py", line 4, in
> from bot.utils.launcher import process
> File "C:\TapSwapBot\bot\utils__init__.py", line 2, in
> from . import launcher
> File "C:\TapSwapBot\bot\utils\launcher.py", line 9, in
> from bot.core.tapper import run_tapper
> File "C:\TapSwapBot\bot\core\tapper.py", line 7, in
> from aiocfscrape import CloudflareScraper
> File "C:\TapSwapBot\venv\Lib\site-packages\aiocfscrape__init__.py", line 8, in
> import js2py
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py__init__.py", line 72, in
> from .base import PyJsException
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 2965, in
> @js
> ^^
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
> return PyJsFunction(val, FunctionPrototype)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 1377, in **init**
> cand = fix_js_args(func)
> ^^^^^^^^^^^^^^^^^
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
> code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
> arg = name_translations[inst.arg]
> ~~~~~~~~~~~~~~~~~^^^^^^^^^^
> KeyError: 3
> I just run Install.bat > enter API > run start.bat and this error pops up. what did i miss
![Screenshot 2024-08-25 160045](https://github.com/user-attachments/assets/16310af6-278c-4c85-8660-1e7ea46f87b3)


same me :(

**Comment by tektungg** [comment]
> > # PS C:\TapSwapBot> python main.py
> > Traceback (most recent call last):
> > File "C:\TapSwapBot\main.py", line 4, in
> > from bot.utils.launcher import process
> > File "C:\TapSwapBot\bot\utils__init__.py", line 2, in
> > from . import launcher
> > File "C:\TapSwapBot\bot\utils\launcher.py", line 9, in
> > from bot.core.tapper import run_tapper
> > File "C:\TapSwapBot\bot\core\tapper.py", line 7, in
> > from aiocfscrape import CloudflareScraper
> > File "C:\TapSwapBot\venv\Lib\site-packages\aiocfscrape__init__.py", line 8, in
> > import js2py
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py__init__.py", line 72, in
> > from .base import PyJsException
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 2965, in
> > @js
> > ^^
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
> > return PyJsFunction(val, FunctionPrototype)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 1377, in **init**
> > cand = fix_js_args(func)
> > ^^^^^^^^^^^^^^^^^
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
> > code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
> > arg = name_translations[inst.arg]
> > ```
> > KeyError: 3
> > I just run Install.bat > enter API > run start.bat and this error pops up. what did i miss
> > ```
> 
> ![Screenshot 2024-08-25 160045](https://private-user-images.githubusercontent.com/153362997/361234965-16310af6-278c-4c85-8660-1e7ea46f87b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTYzMzYsIm5iZiI6MTcyNDU5NjAzNiwicGF0aCI6Ii8xNTMzNjI5OTcvMzYxMjM0OTY1LTE2MzEwYWY2LTI3OGMtNGM4NS04NjYwLTFlN2VhNDZmODdiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxNDI3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjAzOTAxMjI2MmY3ZWNiOTZiNjE0NjZjMTA4MDk0NGQ5N2Q2OTgyNmE0NDAwY2JmN2ZhZmUyNTljYzg0Y2Y3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ctOauoXK4cQqmMmWh2dceDNAL8wAYbKcayAB2zeFNYk)
> 
> same me :(

noooo don't post your API here 😭

**Comment by shamhi** [comment]
Use python 3.11
