### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yahia912** [shamhi/TapSwapBot#219]
2024-09-07 14:55:16 | INFO     | 112 - Downloading webdriver. It may take some time...
/bin/sh: line 1: google-chrome: command not found
/bin/sh: line 1: google-chrome-stable: command not found
/bin/sh: line 1: google-chrome-beta: command not found
/bin/sh: line 1: google-chrome-dev: command not found
/bin/sh: line 1: google-chrome: command not found
/bin/sh: line 1: google-chrome-stable: command not found
/bin/sh: line 1: google-chrome-beta: command not found
/bin/sh: line 1: google-chrome-dev: command not found
Traceback (most recent call last):
  File "/home/shortigamez/TapSwapBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/shortigamez/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/shortigamez/TapSwapBot/bot/utils/launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "/home/shortigamez/TapSwapBot/bot/core/tapper.py", line 17, in <module>
    from bot.utils.scripts import escape_html, login_in_browser
  File "/home/shortigamez/TapSwapBot/bot/utils/scripts.py", line 114, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
  File "/home/shortigamez/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/home/shortigamez/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "/home/shortigamez/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
  File "/home/shortigamez/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/core/driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "/home/shortigamez/TapSwapBot/venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Mtwserv** [comment]
I'm also have the issue with chromedriver 
 ERROR    | 105 - W1 | Unknown error while Login: [WinError 193] %1 is not a valid Win32 application | Response text: ...

I added chromedriver.exe to this DIR  ~\TapSwapBot\webdriver\ but it didn't help.


![Screenshot_1](https://github.com/user-attachments/assets/f7c4313d-3014-4a1b-8d88-177f99f441b3)

**Comment by yahia912** [comment]
Thanks for the Help! Though I'm running it on linux, will this work?
