### ISSUE TITLE
Cannot start bot from new clone with USE_PROXY_FROM_FILE=False configuration

### ISSUE THREAD

**Issue by dashcappitain** [shamhi/TapSwapBot#31]
Hello,

I can not start bot from new clone with USE_PROXY_FROM_FILE=False configuration

I get this error message

(venv) root@vmi1776592:~/TapSwapBot# python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.8/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.8/site-packages/better_proxy/proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

please help

**Comment by shamhi** [comment]
use python 3.10 or 3.11
