### ISSUE TITLE
Error after last commit

### ISSUE THREAD

**Issue by krava77** [shamhi/TapSwapBot#46]
Здравствуйте
Вот такую ошибку получаю после последнего коммита. Как ее можно решить?

`/TapSwapBot# python3 tws_coin.py -a 2
Traceback (most recent call last):
  File "/root/TapSwapBot/tws_coin.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/root/TapSwapBot/bot/core/tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "/usr/local/lib/python3.12/dist-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/usr/local/lib/python3.12/dist-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
`

**Comment by asyv3n** [comment]
там новый пакет добавили, не забыл обновить зависимости?
`pip3 install -r requirements.txt`

**Comment by Desamod** [comment]
У тебя питон 3.12, поставь 3.10 или 3.11

**Comment by ATAMAH161** [comment]
> У тебя питон 3.12, поставь 3.10 или 3.11

а если стоит и 3.12 и 3.11 он же сам разберется с какого запускать?

**Comment by krava77** [comment]
> там новый пакет добавили, не забыл обновить зависимости? `pip3 install -r requirements.txt`

Разумеется, загрузил и обновил все компоненты

**Comment by krava77** [comment]
> У тебя питон 3.12, поставь 3.10 или 3.11
Странно конечно, раньше без проблем на 3.12 работало. попробую и отпишусь здесь

**Comment by krava77** [comment]
> > У тебя питон 3.12, поставь 3.10 или 3.11
> 
> а если стоит и 3.12 и 3.11 он же сам разберется с какого запускать?

Нет, по умолчанию загружается тот который установлен дефорлным, нужно либо поменять версию пайтона по умолчанию, либо указывать полный путь к загрузочному файту пайтона, например /usr/bin/python3.10

**Comment by fly-a1one** [comment]
> Нет, по умолчанию загружается тот который установлен дефорлным, нужно либо поменять версию пайтона по умолчанию, либо указывать полный путь к загрузочному файту пайтона, например /usr/bin/python3.10

А если по дефолту стоит 3.12, то как откатить на версию ниже или установить дополнительную?

**Comment by ATAMAH161** [comment]
> > Нет, по умолчанию загружается тот который установлен дефорлным, нужно либо поменять версию пайтона по умолчанию, либо указывать полный путь к загрузочному файту пайтона, например /usr/bin/python3.10
> 
> А если по дефолту стоит 3.12, то как откатить на версию ниже или установить дополнительную?

В поисковике есть ответ схемы как это сделать. Там задаётся приоритет для нужной версии

**Comment by stwn11** [comment]
same issue here, how to fix?

**Comment by krava77** [comment]
> same issue here, how to fix?

with python 3.11 everything works well

**Comment by stwn11** [comment]
> > same issue here, how to fix?
> 
> with python 3.11 everything works well

thanks bro, works well
