### ISSUE TITLE
Erorr when py main.py and pip install -r requirements

### ISSUE THREAD

**Issue by 0xsiwant** [shamhi/TapSwapBot#47]
:\Users\_WhatYourDream_\Downloads\TapSwapBot\TapSwapBot-main>py main.py
Traceback (most recent call last):
  File "C:\Users\_WhatYourDream_\Downloads\TapSwapBot\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\_WhatYourDream_\Downloads\TapSwapBot\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\_WhatYourDream_\Downloads\TapSwapBot\TapSwapBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\_WhatYourDream_\Downloads\TapSwapBot\TapSwapBot-main\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Python312\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by shamhi** [comment]
use python 3.10 or 3.11
