### ISSUE TITLE
'response_text

### ISSUE THREAD

**Issue by xcybermanx** [shamhi/TapSwapBot#48]
hello how can fix this issue :

2024-05-30 20:54:44 | ERROR    | 348 - tap | Unknown error: local variable 'response_text' referenced before assignment

**Comment by MortezaVaezi2005** [comment]
ERROR    | 348 - Morteza | Unknown error: cannot access local variable 'response_text' where it is notassociated with a value

i have it too🚶🚶🚶

**Comment by xcybermanx** [comment]
i have update to tast version but always this Error Yestap waork Great but tapswap no

**Comment by Stockgolm** [comment]
Traceback (most recent call last):
  File "/home/TapSwapBot-main/TapSwapBot-main/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/TapSwapBot-main/TapSwapBot-main/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/TapSwapBot-main/TapSwapBot-main/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/home/TapSwapBot-main/TapSwapBot-main/bot/core/tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TapSwapBot-main/TapSwapBot-main/env/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
