### ISSUE TITLE
Exception, after 1-5hours work.

### ISSUE THREAD

**Issue by daeeros** [shamhi/TapSwapBot#53]
```
Traceback (most recent call last):
  File "/root/TapSwapBot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/root/miniforge3/envs/tapbot/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/tapbot/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/tapbot/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/TapSwapBot/main.py", line 8, in main
    await process()
  File "/root/TapSwapBot/bot/utils/launcher.py", line 102, in process
    await run_tasks(tg_clients=tg_clients)
  File "/root/TapSwapBot/bot/utils/launcher.py", line 124, in run_tasks
    await asyncio.gather(*tasks)
  File "/root/TapSwapBot/bot/core/tapper.py", line 375, in run_tapper
    await Tapper(tg_client=tg_client).run(proxy=proxy)
  File "/root/TapSwapBot/bot/core/tapper.py", line 360, in run
    logger.error(f"{self.session_name} | Unknown error: {error}")
  File "/root/miniforge3/envs/tapbot/lib/python3.11/site-packages/loguru/_logger.py", line 2056, in error
    __self._log("ERROR", False, __self._options, __message, args, kwargs)
  File "/root/miniforge3/envs/tapbot/lib/python3.11/site-packages/loguru/_logger.py", line 2017, in _log
    colored_message = Colorizer.prepare_simple_message(str(message))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/tapbot/lib/python3.11/site-packages/loguru/_colorizer.py", line 368, in prepare_simple
_message
    parser.feed(string)
  File "/root/miniforge3/envs/tapbot/lib/python3.11/site-packages/loguru/_colorizer.py", line 252, in feed
    raise ValueError(
ValueError: Tag "<html>" does not correspond to any known color directive, make sure you did not misspelled it (or p
repend '\' to escape it)
```

**Comment by BloodyKatana47** [comment]
Same

**Comment by monkiravn** [comment]
Tapswap's API was down. Retry 2-3 hours later, guys

**Comment by krava77** [comment]
Create a bash script that checks if TWS is running, if not, execute it again. Please note, the name of the script should be unique.
for example: 
`
if ! ps -ef | grep -v grep | grep -q tws_coin.py; > /dev/null
then
	nohup /usr/bin/python3.11 tws_coin.py -a 2 & > /dev/null
fi


while sleep 1000; do
	if ! ps -ef | grep -v grep | grep -q tws_coin.py; > /dev/null
	then
		nohup /usr/bin/python3.11 tws_coin.py -a 2 & > /dev/null
	fi
done
`
