### ISSUE TITLE
SLEEP_BY_MIN_ENERGY

### ISSUE THREAD

**Issue by pamskye** [shamhi/TapSwapBot#63]
Traceback (most recent call last):
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\config\config.py", line 31, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid list [type=list_type, input_value=2400, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by Mohammad5-M** [comment]
what is the value of your SLEEP_BY_MIN_ENERGY in .env file?

**Comment by Mohammad5-M** [comment]
its should be a list like this [1800,2400].

**Comment by pamskye** [comment]
Input should be a valid list [type=list_type, input_value=2400, input_type=int]

**Comment by Mohammad5-M** [comment]
As I said, you just put an int number, it should be a range of numbers.
like [1800,2400].

**Comment by pamskye** [comment]
> As I said, you just put an int number, it should be a range of numbers. like [1800,2400].

Traceback (most recent call last):
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sbyte\OneDrive\Masaüstü\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by pamskye** [comment]
MIN_AVAILABLE_ENERGY=50
SLEEP_BY_MIN_ENERGY = [1800,3600,5400] 

ADD_TAPS_ON_TURBO=

AUTO_UPGRADE_TAP=False
MAX_TAP_LEVEL=5
AUTO_UPGRADE_ENERGY=False
MAX_ENERGY_LEVEL=5
AUTO_UPGRADE_CHARGE=False
MAX_CHARGE_LEVEL=5

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=
SLEEP_BETWEEN_TAP=
USE_PROXY_FROM_FILE=
