### ISSUE TITLE
Error - Troubles with start

### ISSUE THREAD

**Issue by azariallev** [shamhi/TapSwapBot#70]
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "d:\TGScripts\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "d:\TGScripts\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "d:\TGScripts\TapSwapBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "d:\TGScripts\TapSwapBot-main\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\TGScripts\TapSwapBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
Для продолжения нажмите любую клавишу . . .

**Comment by azariallev** [comment]
Несколько раз переустанавливал, удалял, запускал - уткнулся в ошибку, никак разобраться не могу

**Comment by borcrypto** [comment]
Same issue

**Comment by stebashaDM** [comment]
same issue

**Comment by Savata-Rayma** [comment]
js2py is not supported in Python 3.12, I recommend installing Python 3.11.9.

**Comment by azariallev** [comment]
On board 3.12.4 ...

> js2py is not supported in Python 3.12, I recommend installing Python 3.11.9.

**Comment by azariallev** [comment]
oy, I understand
