### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mkawey100** [shamhi/TapSwapBot#75]
Traceback (most recent call last):
  File "C:\Users\mk\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\mk\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\mk\TapSwapBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\mk\TapSwapBot\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mk\TapSwapBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]

**Comment by Savata-Rayma** [comment]
js2py is not supported in Python 3.12, I recommend installing Python 3.11.9.

**Comment by SireJeff** [comment]
2024-06-08 23:13:06 | ERROR    | 83 - mine | Unknown error while getting Access 
Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-08 23:13:07 | ERROR    | 83 - jeff | Unknown error while getting Access 
Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
