### ISSUE TITLE
Unknown error when Tapping: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/player/submit_taps') | Response text: {"statusCode":400,"message":"invalid_taps"}...

### ISSUE THREAD

**Issue by tertaco** [shamhi/TapSwapBot#78]
I'm getting next error:
`2024-06-12 14:53:04 | ERROR    | 186 - DESKTOP-CDIH62G | Unknown error when Tapping: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/player/submit_taps') | Response text: {"statusCode":400,"message":"invalid_taps"}...`

![image](https://github.com/shamhi/TapSwapBot/assets/76095170/7baecad5-13fd-4b4e-89e8-c6f9b69e7e9b)

**Comment by rippomane** [comment]
same

**Comment by razak95** [comment]
same here

**Comment by Dumpff** [comment]
same

**Comment by Kit0077** [comment]
+

**Comment by davletbaevtr** [comment]
same

**Comment by MortezaVaezi2005** [comment]
same

**Comment by general12345** [comment]
+

**Comment by headNbyte** [comment]
Hey folks. I fixed it using Selenium, no more need to use Regex.

**1. Add following lines to the requirements.txt:**
```
selenium==4.21.0
webdriver-manager==4.0.1
```
**2. Update libraries using this command:**
`pip install -r requirements.txt`

**3. Replace function extract_chq in the bot/utils/scripts.py and the libraries at the top**
```
import asyncio
from typing import Union

from pyrogram import Client
from pyrogram.types import Message

from bot.utils.emojis import num, StaticEmoji
from bs4 import BeautifulSoup

import pathlib
import shutil
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options as ChromeOptions
from webdriver_manager.chrome import ChromeDriverManager
```
```
def extract_chq(chq: str) -> int:
    if not pathlib.Path("webdriver").exists():
        pathlib.Path("webdriver").mkdir(parents=True)
        webdriver_path = pathlib.Path(ChromeDriverManager().install())
        shutil.move(webdriver_path, f"webdriver/{webdriver_path.name}")
    else:
        webdriver_path = next(pathlib.Path("webdriver").iterdir()).as_posix()

    chq_length = len(chq)

    bytes_array = bytearray(chq_length // 2)
    xor_key = 157

    for i in range(0, chq_length, 2):
        bytes_array[i // 2] = int(chq[i:i + 2], 16)

    xor_bytes = bytearray(t ^ xor_key for t in bytes_array)
    decoded_xor = xor_bytes.decode('utf-8')

    options = ChromeOptions()
    options.add_argument("--headless")
    driver = webdriver.Chrome(service=ChromeService(webdriver_path), options=options)

    driver.execute_script("""
        var chrStub = document.createElement("div");
        chrStub.id = "_chr_";
        document.body.appendChild(chrStub);
    """)

    fixed_xor = repr(decoded_xor).replace("`", "\\`")

    k = driver.execute_script(f"""
        try {{
            return eval(`{fixed_xor[1:-1]}`);
        }} catch (e) {{
            return e;
        }}
    """)

    driver.quit()

    return k

```

**4. [DOCKER USERS ONLY] add webdriver to .gitignore if you are using different host and container OS. You might want to switch to another webdriver like Gecko. Please make sure to edit the code.**
**5. Provide feedback or just react to this comment via emoji**

Good luck!

**Comment by Kit0077** [comment]
> Привет, ребята. Я исправил это с помощью Selenium, больше нет необходимости использовать регулярные выражения.
> 
> **1. Добавьте следующие строки в requirements.txt:**
> 
> ```
> selenium==4.21.0
> webdriver-manager==4.0.1
> ```
> 
> **2. Обновите библиотеки с помощью этой команды:** `pip install -r requirements.txt`
> 
> **3. Замените функцию extract_chq в bot/utils/scripts.py и библиотеки вверху**
> 
> ```
> import asyncio
> from typing import Union
> 
> from pyrogram import Client
> from pyrogram.types import Message
> 
> from bot.utils.emojis import num, StaticEmoji
> from bs4 import BeautifulSoup
> 
> import pathlib
> import shutil
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service as ChromeService
> from selenium.webdriver.chrome.options import Options as ChromeOptions
> from webdriver_manager.chrome import ChromeDriverManager
> ```
> 
> ```
> def extract_chq(chq: str) -> int:
>     if not pathlib.Path("webdriver").exists():
>         pathlib.Path("webdriver").mkdir(parents=True)
>         webdriver_path = pathlib.Path(ChromeDriverManager().install())
>         shutil.move(webdriver_path, f"webdriver/{webdriver_path.name}")
> 
>     webdriver_path = next(pathlib.Path("webdriver").iterdir()).as_posix()
> 
>     chq_length = len(chq)
> 
>     bytes_array = bytearray(chq_length // 2)
>     xor_key = 157
> 
>     for i in range(0, chq_length, 2):
>         bytes_array[i // 2] = int(chq[i:i + 2], 16)
> 
>     xor_bytes = bytearray(t ^ xor_key for t in bytes_array)
>     decoded_xor = xor_bytes.decode('utf-8')
> 
>     options = ChromeOptions()
>     options.add_argument("--headless")
>     driver = webdriver.Chrome(service=ChromeService(webdriver_path), options=options)
> 
>     driver.execute_script("""
>         var chrStub = document.createElement("div");
>         chrStub.id = "_chr_";
>         document.body.appendChild(chrStub);
>     """)
> 
>     fixed_xor = repr(decoded_xor).replace("`", "\\`")
> 
>     k = driver.execute_script(f"""
>         try {{
>             return eval(`{fixed_xor[1:-1]}`);
>         }} catch (e) {{
>             return e;
>         }}
>     """)
> 
>     driver.quit()
> 
>     return k
> ```
> 
> **4. [ИСПРАВЛЕНИЕ ДЛЯ НЕСКОЛЬКИХ УЧЕТНЫХ записей] Для нескольких учетных записей вам нужно создать блокировку asyncio внутри bot/utils/launcher.py, а затем применить это в самом tapper внутри метода входа в систему.**
> 
> **4.1. bot/utils/launcher.py**
> 
> ```
> async def run_tasks(tg_clients: list[Client]):
>     proxies = get_proxies()
>     proxies_cycle = cycle(proxies) if proxies else None
>     lock = asyncio.Lock()
> 
>     tasks = [
>         asyncio.create_task(
>             run_tapper(
>                 tg_client=tg_client,
>                 proxy=next(proxies_cycle) if proxies_cycle else None,
>                 lock=lock,
>             )
>         )
>         for tg_client in tg_clients
>     ]
> 
>     await asyncio.gather(*tasks)
> ```
> 
> **4.2. bot/core/tapper.py**
> 
> ```
> class Tapper:
>     def __init__(self, tg_client: Client, lock: asyncio.Lock):
>         self.session_name = tg_client.name
>         self.tg_client = tg_client
>         self.user_id = 0
>         self.lock = lock
> ```
> 
> ```
>   async def login(self, http_client: aiohttp.ClientSession, tg_web_data: str) -> tuple[dict[str], str]:
>        response_text = ''
>        try:
>            response = await http_client.post(url='https://api.tapswap.ai/api/account/login',
>                                              json={"init_data": tg_web_data, "referrer": ""})
>            response_text = await response.text()
>            response.raise_for_status()
> 
>            response_json = await response.json()
>            wait_s = response_json.get('wait_s')
>            if wait_s:
>                logger.error(f"{self.session_name} | App overloaded, waiting for: {wait_s}")
>                await asyncio.sleep(delay=wait_s)
>                return self.login(http_client, tg_web_data)
> 
>            chq = response_json.get('chq')
> 
>            if chq:
>                async with self.lock:
>                    chq_result = extract_chq(chq=chq)
> 
>                    response = await http_client.post(url='https://api.tapswap.ai/api/account/login',
>                                                    json={"chr": chq_result, "init_data": tg_web_data, "referrer": ""})
>                    response_text = await response.text()
>                    response.raise_for_status()
> ```
> 
> **5. [ТОЛЬКО ДЛЯ ПОЛЬЗОВАТЕЛЕЙ DOCKER] добавьте webdriver в .gitignore, если вы используете другую ОС хостинга и контейнера. Возможно, вы захотите переключиться на другой webdriver, например Gecko. Пожалуйста, обязательно отредактируйте код.** **5.1. bot/utils/scripts.py **
> 
> ```
> import asyncio
> from typing import Union
> 
> from pyrogram import Client
> from pyrogram.types import Message
> 
> from bot.utils.emojis import num, StaticEmoji
> from bs4 import BeautifulSoup
> 
> import pathlib
> import shutil
> from selenium import webdriver
> from selenium.webdriver.firefox.service import Service as FirefoxService
> from selenium.webdriver.firefox.options import Options as FirefoxOptions
> from webdriver_manager.firefox import GeckoDriverManager
> ```
> 
> ```
> def extract_chq(chq: str) -> int:
>     if not pathlib.Path("webdriver").exists():
>         pathlib.Path("webdriver").mkdir(parents=True)
>         webdriver_path = pathlib.Path(GeckoDriverManager().install())
>         shutil.move(webdriver_path, f"webdriver/{webdriver_path.name}")
> 
>     webdriver_path = next(pathlib.Path("webdriver").iterdir()).as_posix()
> 
>     chq_length = len(chq)
> 
>     bytes_array = bytearray(chq_length // 2)
>     xor_key = 157
> 
>     for i in range(0, chq_length, 2):
>         bytes_array[i // 2] = int(chq[i:i + 2], 16)
> 
>     xor_bytes = bytearray(t ^ xor_key for t in bytes_array)
>     decoded_xor = xor_bytes.decode('utf-8')
> 
>     options = FirefoxOptions()
>     options.add_argument("--headless")
>     driver = webdriver.Firefox(service=FirefoxService(webdriver_path), options=options)
> 
>     driver.execute_script("""
>         var chrStub = document.createElement("div");
>         chrStub.id = "_chr_";
>         document.body.appendChild(chrStub);
>     """)
> 
>     fixed_xor = repr(decoded_xor).replace("`", "\\`")
> 
>     k = driver.execute_script(f"""
>         try {{
>             return eval(`{fixed_xor[1:-1]}`);
>         }} catch (e) {{
>             return e;
>         }}
>     """)
> 
>     driver.quit()
> 
>     return k
> ```
> 
> **5.2. Добавьте строку в Dockerfile перед установкой pip** `RUN apk add --no-cache firefox` **5.3. Создайте .dockerignore, если он не существует, и добавьте эту строку** `webdriver`
> 
> **6. Оставьте отзыв или просто отреагируйте на этот комментарий с помощью смайлика**
> 
> Удачи!

Bro, thank you very much for your efforts. Could you post the finished files with the modified code, for those who are not good at programming, like me))

**Comment by headNbyte** [comment]
On my way to create a fork...

**Comment by headNbyte** [comment]
Here is an all-in-one solution for Windows, Linux and Docker

https://github.com/headNbyte/TapSwapBot/tree/main

**Comment by razak95** [comment]
> Hey folks. I fixed it using Selenium, no more need to use Regex.
> 
> **1. Add following lines to the requirements.txt:**
> 
> ```
> selenium==4.21.0
> webdriver-manager==4.0.1
> ```
> 
> **2. Update libraries using this command:** `pip install -r requirements.txt`
> 
> **3. Replace function extract_chq in the bot/utils/scripts.py and the libraries at the top**
> 
> ```
> import asyncio
> from typing import Union
> 
> from pyrogram import Client
> from pyrogram.types import Message
> 
> from bot.utils.emojis import num, StaticEmoji
> from bs4 import BeautifulSoup
> 
> import pathlib
> import shutil
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service as ChromeService
> from selenium.webdriver.chrome.options import Options as ChromeOptions
> from webdriver_manager.chrome import ChromeDriverManager
> ```
> 
> ```
> def extract_chq(chq: str) -> int:
>     if not pathlib.Path("webdriver").exists():
>         pathlib.Path("webdriver").mkdir(parents=True)
>         webdriver_path = pathlib.Path(ChromeDriverManager().install())
>         shutil.move(webdriver_path, f"webdriver/{webdriver_path.name}")
> 
>     webdriver_path = next(pathlib.Path("webdriver").iterdir()).as_posix()
> 
>     chq_length = len(chq)
> 
>     bytes_array = bytearray(chq_length // 2)
>     xor_key = 157
> 
>     for i in range(0, chq_length, 2):
>         bytes_array[i // 2] = int(chq[i:i + 2], 16)
> 
>     xor_bytes = bytearray(t ^ xor_key for t in bytes_array)
>     decoded_xor = xor_bytes.decode('utf-8')
> 
>     options = ChromeOptions()
>     options.add_argument("--headless")
>     driver = webdriver.Chrome(service=ChromeService(webdriver_path), options=options)
> 
>     driver.execute_script("""
>         var chrStub = document.createElement("div");
>         chrStub.id = "_chr_";
>         document.body.appendChild(chrStub);
>     """)
> 
>     fixed_xor = repr(decoded_xor).replace("`", "\\`")
> 
>     k = driver.execute_script(f"""
>         try {{
>             return eval(`{fixed_xor[1:-1]}`);
>         }} catch (e) {{
>             return e;
>         }}
>     """)
> 
>     driver.quit()
> 
>     return k
> ```
> 
> **4. [MULTIACCOUNTS FIX] For multiaccounts you need to create an asyncio lock inside the bot/utils/launcher.py and then apply this in the tapper itself inside the login method.**
> 
> **4.1. bot/utils/launcher.py**
> 
> ```
> async def run_tasks(tg_clients: list[Client]):
>     proxies = get_proxies()
>     proxies_cycle = cycle(proxies) if proxies else None
>     lock = asyncio.Lock()
> 
>     tasks = [
>         asyncio.create_task(
>             run_tapper(
>                 tg_client=tg_client,
>                 proxy=next(proxies_cycle) if proxies_cycle else None,
>                 lock=lock,
>             )
>         )
>         for tg_client in tg_clients
>     ]
> 
>     await asyncio.gather(*tasks)
> ```
> 
> **4.2. bot/core/tapper.py**
> 
> ```
> class Tapper:
>     def __init__(self, tg_client: Client, lock: asyncio.Lock):
>         self.session_name = tg_client.name
>         self.tg_client = tg_client
>         self.user_id = 0
>         self.lock = lock
> ```
> 
> ```
>   async def login(self, http_client: aiohttp.ClientSession, tg_web_data: str) -> tuple[dict[str], str]:
>        response_text = ''
>        try:
>            response = await http_client.post(url='https://api.tapswap.ai/api/account/login',
>                                              json={"init_data": tg_web_data, "referrer": ""})
>            response_text = await response.text()
>            response.raise_for_status()
> 
>            response_json = await response.json()
>            wait_s = response_json.get('wait_s')
>            if wait_s:
>                logger.error(f"{self.session_name} | App overloaded, waiting for: {wait_s}")
>                await asyncio.sleep(delay=wait_s)
>                return self.login(http_client, tg_web_data)
> 
>            chq = response_json.get('chq')
> 
>            if chq:
>                async with self.lock:
>                    chq_result = extract_chq(chq=chq)
> 
>                    response = await http_client.post(url='https://api.tapswap.ai/api/account/login',
>                                                    json={"chr": chq_result, "init_data": tg_web_data, "referrer": ""})
>                    response_text = await response.text()
>                    response.raise_for_status()
> ```
> 
> **5. [DOCKER USERS ONLY] add webdriver to .gitignore if you are using different host and container OS. You might want to switch to another webdriver like Gecko. Please make sure to edit the code.** **5.1. bot/utils/scripts.py**
> 
> ```
> import asyncio
> from typing import Union
> 
> from pyrogram import Client
> from pyrogram.types import Message
> 
> from bot.utils.emojis import num, StaticEmoji
> from bs4 import BeautifulSoup
> 
> import pathlib
> import shutil
> from selenium import webdriver
> from selenium.webdriver.firefox.service import Service as FirefoxService
> from selenium.webdriver.firefox.options import Options as FirefoxOptions
> from webdriver_manager.firefox import GeckoDriverManager
> ```
> 
> ```
> def extract_chq(chq: str) -> int:
>     if not pathlib.Path("webdriver").exists():
>         pathlib.Path("webdriver").mkdir(parents=True)
>         webdriver_path = pathlib.Path(GeckoDriverManager().install())
>         shutil.move(webdriver_path, f"webdriver/{webdriver_path.name}")
> 
>     webdriver_path = next(pathlib.Path("webdriver").iterdir()).as_posix()
> 
>     chq_length = len(chq)
> 
>     bytes_array = bytearray(chq_length // 2)
>     xor_key = 157
> 
>     for i in range(0, chq_length, 2):
>         bytes_array[i // 2] = int(chq[i:i + 2], 16)
> 
>     xor_bytes = bytearray(t ^ xor_key for t in bytes_array)
>     decoded_xor = xor_bytes.decode('utf-8')
> 
>     options = FirefoxOptions()
>     options.add_argument("--headless")
>     driver = webdriver.Firefox(service=FirefoxService(webdriver_path), options=options)
> 
>     driver.execute_script("""
>         var chrStub = document.createElement("div");
>         chrStub.id = "_chr_";
>         document.body.appendChild(chrStub);
>     """)
> 
>     fixed_xor = repr(decoded_xor).replace("`", "\\`")
> 
>     k = driver.execute_script(f"""
>         try {{
>             return eval(`{fixed_xor[1:-1]}`);
>         }} catch (e) {{
>             return e;
>         }}
>     """)
> 
>     driver.quit()
> 
>     return k
> ```
> 
> **5.2. Add line to Dockerfile before pip install** `RUN apk add --no-cache firefox` **5.3. Create .dockerignore if not exists and add this line** `webdriver`
> 
> **6. Provide feedback or just react to this comment via emoji**
> 
> Good luck!

bro, i got another error 
![image](https://github.com/shamhi/TapSwapBot/assets/15963928/961b9b35-137e-46ea-ae68-df960dd47b18)

**Comment by headNbyte** [comment]
@razak95 Hey friend!
I'm sorry, my mistake in the manual.
I forgot to add this code to the bot/core/tapper.py

```
async def run_tapper(tg_client: Client, proxy: str | None, lock: asyncio.Lock):
    try:
        await Tapper(tg_client=tg_client, lock=lock).run(proxy=proxy)
    except InvalidSession:
        logger.error(f"{tg_client.name} | Invalid Session")
```

Also you can check out my fork with the optimized code with fixes that were not developed at the time when I posted the tutorial:
https://github.com/headNbyte/TapSwapBot/tree/main

**Comment by Kit0077** [comment]
> @razak95 Hey friend! I'm sorry, my mistake in the manual. I forgot to add this code to the bot/core/tapper.py
> 
> ```
> async def run_tapper(tg_client: Client, proxy: str | None, lock: asyncio.Lock):
>     try:
>         await Tapper(tg_client=tg_client, lock=lock).run(proxy=proxy)
>     except InvalidSession:
>         logger.error(f"{tg_client.name} | Invalid Session")
> ```
> 
> Also you can check out my fork with the optimized code with fixes that were not developed at the time when I posted the tutorial: https://github.com/headNbyte/TapSwapBot/tree/main

Hello bro! I get this when running your script, what can I do?
![image](https://github.com/shamhi/TapSwapBot/assets/57114371/66f5a6d9-36e4-4695-88b3-4a6f8a54c944)

**Comment by razak95** [comment]
> > @razak95 Hey friend! I'm sorry, my mistake in the manual. I forgot to add this code to the bot/core/tapper.py
> > ```
> > async def run_tapper(tg_client: Client, proxy: str | None, lock: asyncio.Lock):
> >     try:
> >         await Tapper(tg_client=tg_client, lock=lock).run(proxy=proxy)
> >     except InvalidSession:
> >         logger.error(f"{tg_client.name} | Invalid Session")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also you can check out my fork with the optimized code with fixes that were not developed at the time when I posted the tutorial: https://github.com/headNbyte/TapSwapBot/tree/main
> 
> Hello bro! I get this when running your script, what can I do? ![image](https://private-user-images.githubusercontent.com/57114371/339723437-66f5a6d9-36e4-4695-88b3-4a6f8a54c944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTkyMDMsIm5iZiI6MTcxODM1ODkwMywicGF0aCI6Ii81NzExNDM3MS8zMzk3MjM0MzctNjZmNWE2ZDktMzZlNC00Njk1LTg4YjMtNGE2ZjhhNTRjOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYzlkYWYwNjA1YjM2ODRlYjJhYWEyMjkwNGQwOGM2MTNjNGU0NDVkYmZmYTE0NzllMmM3YTNmZDFiZmI5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuZ3OdXoJ8uaZ-KLrwHaoIqEIh6CU9TUyCK46YPzmHk)

![Screenshot_20240614-175113](https://github.com/shamhi/TapSwapBot/assets/15963928/5b366b9d-5c28-4b6b-81f9-6d71fc32ca2b)


Hi frend. I got another problem

**Comment by headNbyte** [comment]
@razak95 you need to run install.sh

**Comment by headNbyte** [comment]
@Kit0077 You need to have Chrome installed on your Windows machine

**Comment by Kit0077** [comment]
> @Kit0077 You need to have Chrome installed on your Windows machine

I'm surprised, I didn't think it was important. And can you find out in a nutshell how it is connected and how it works, at least approximately?

**Comment by headNbyte** [comment]
> > @Kit0077 You need to have Chrome installed on your Windows machine
> 
> I'm surprised, I didn't think it was important. And can you find out in a nutshell how it is connected and how it works, at least approximately?

Selenium uses a binary called webdriver, it's an interface to interact with the installed browser, it creates an empty session on every startup (if no cookies provided in the config). Selenium is capable to visit webpages and scrape the data. But I used it only to run JS code, no pages were visited. The issue is that TapSwap changes their JS code every 2 days and our parser get's broken, so you see those issues. But this approach dynamically calculates the formulas that needed to authenticate and closes the browser.

**Comment by headNbyte** [comment]
@shamhi you can close this issue

**Comment by razak95** [comment]
> @razak95 you need to run install.sh since you don't have firefox installed in your Linux `sh install.sh`
> 
> On Windows you need to have Chrome installed

(venv) root@localhost:~/TapSwapBot# python main.py
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "/root/TapSwapBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/TapSwapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/TapSwapBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.11/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "/root/TapSwapBot/venv/lib/python3.11/site-packages/better_proxy/proxy.py", line 5, in <module>
    from pydantic import BaseModel
  File "/root/TapSwapBot/venv/lib/python3.11/site-packages/pydantic/__init__.py", line 383, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/TapSwapBot/venv/lib/python3.11/site-packages/pydantic/main.py", line 12, in <module>
    import pydantic_core
  File "/root/TapSwapBot/venv/lib/python3.11/site-packages/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: dlopen failed: library "/root/TapSwapBot/venv/lib/python3.11/site-packages/pydantic_core/_pydantic_core.cpython-311.so" needed or dlopened by "/data/data/com.termux/files/usr/lib/libpython3.11.so.1.0" is not accessible for the namespace "(default)"
