### ISSUE TITLE
Bro, another issue

### ISSUE THREAD

**Issue by Mjstq** [shamhi/TapSwapBot#80]
Unknown error while getting
Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/a ccount/login') | Response text: ("statuscode":400, "message";"invalid_request[1]"

**Comment by Mohammad5-M** [comment]
same bro

**Comment by headNbyte** [comment]
Does my fork solve your issues?
https://github.com/headNbyte/TapSwapBot/tree/main

For details what is changed, please take a look at the previous two issues that I contributed to.

**Comment by cardimancom** [comment]
> Does my fork solve your issues? https://github.com/headNbyte/TapSwapBot/tree/main
> 
> For details what is changed, please take a look at the previous two issues that I contributed to.

thanks, this work for me

**Comment by headNbyte** [comment]
@shamhi you can close this issue

**Comment by Mjstq** [comment]
Doesn’t work for me, error:

{"chq":"fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbdeda0c6baafaaada8a5abeaffc8e5fffcbab1baaca8f0d7fcefdcf7bab1baacafa8aba8afa9f6efd9cbd0dbbab1baa8f1dbfcf6cbf8bab1baaea5adabacadaddac7d0d9d1fabab1baaeafabafaaadaaedd8ebd6d6d2bab1baaeaba4aaa8a5a9f4c7f8f1efcfbab1baacafa5aaa8abaaf2dac9ecd7d6bab1baacadfeccd6e9d1eebab1baacaeaeaaa5a5c7f4cfd9dcdcbac0a6fca0fbe8f3fee9f4f2f3b5b4e6eff8e9e8eff3bdeda6e0a6eff8e9e8eff3bdfcb5b4a6e0fbe8f3fee9f4f2f3bdffb5feb1f9b4e6ebfcefbdf8a0fcb5b4a6eff8e9e8eff3bdffa0fbe8f3fee9f4f2f3b5fbb1fab4e6fba0fbb0ade5aaffa6ebfcefbdf5a0f8c6fbc0a6eff8e9e8eff3bdf5a6e0b1ffb5feb1f9b4a6e0b5fbe8f3fee9f4f2f3b5feb1f9b4e6ebfcefbdf2a0ffb1f8a0feb5b4a6eaf5f4f1f8b5bcbcc6c0b4e6e9efe4e6ebfcefbdfba0edfcefeef8d4f3e9b5f2b5ade5aaffb4b4b2ade5acb6b0edfcefeef8d4f3e9b5f2b5ade5aafeb4b4b2ade5afb7b5b0edfcefeef8d4f3e9b5f2b5ade5aaf9b4b4b2ade5aeb4b6edfcefeef8d4f3e9b5f2b5ade5aaf8b4b4b2ade5a9b7b5edfcefeef8d4f3e9b5f2b5ade5aafbb4b4b2ade5a8b4b6b0edfcefeef8d4f3e9b5f2b5ade5a5adb4b4b2ade5abb6b0edfcefeef8d4f3e9b5f2b5ade5a5acb4b4b2ade5aab6edfcefeef8d4f3e9b5f2b5ade5a5afb4b4b2ade5a5b6b0edfcefeef8d4f3e9b5f2b5ade5a5aeb4b4b2ade5a4b7b5edfcefeef8d4f3e9b5f2b5ade5a5a9b4b4b2ade5fcb4a6f4fbb5fba0a0a0f9b4ffeff8fcf6a6f8f1eef8bdf8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0fefce9fef5b5fab4e6f8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0e0e0b5fcb1ade5a8aefeacfeb4b1b5fbe8f3fee9f4f2f3b5b4e6ebfcefbdf8a0e6e0a6f8c6bae9d7f8c8f0bac0a0bafaf8e9d8f1f8f0f8f3e9dfe4d4f9bab1f8c6baf7e9d5d6e8bac0a0bafaf8e9dce9e9eff4ffe8e9f8bab1f8c6badcebf8eccbbac0a0bac2fef5efc2bab1f8c6bafec9dcfcecbac0a0baf4f3f3f8efd5c9d0d1bab1f8c6baebf2fcf5eebac0a0bac2dffbc2adbaa6ebfcefbdfba0f8a6e9efe4e6f8ebfcf1b5baf9f2fee8f0f8f3e9c6c1bafaf8e9d8f1f8f0f8f3e9dfe4d4f9c1bac0a6bab4a6e0fefce9fef5e6eff8e9e8eff3bdade5feadfbf8fffcfff8a6e0ebfcefbdf5a0f9f2fee8f0f8f3e9b1f4a0fbc6bae9d7f8c8f0bac0b1f7a0fbc6baf7e9d5d6e8bac0b1f6a0f5c6f4c0b5fbc6badcebf8eccbbac0b4a6f6c6fbc6bafec9dcfcecbac0c0a0baa1f9f4eba3a1f9f4ebc1e5afadf4f9a0c1e5afafc2dffbc2adc1e5afafbab6bac1e5afadc2eba0c1e5afafacafa9aea8c1e5afafa3a1f9f4ebc1e5afadf4f9a0bab6bac1e5afafc2edafc2acc1e5afafc1e5afadc2eba0c1e5afafaeaeaea4a5c1e5afafa3a1bab6baf9f4ebc1e5afadf4f9a0c1e5afafc2f4f8c2afc1e5afafc1e5afadc2eba0c1e5afafa9bab6baafada9a5c1e5afafa3a1f9f4ebc1e5afadf4f9a0c1e5afafc2f6a9c2aebab6bac1e5afafc1e5afadc2eba0c1e5afafa9acadaea8c1e5afafa3a1f9f4ebc1e5afadf4f9bab6baa0c1e5afafc2f1a4c2a9c1e5afafc1e5afadc2eba0c1e5afafa5a4a8a5aac1e5afafa3bab6baa1b2f9f4eba3a1b2f9f4eba3a1b2f9f4eba3a1b2bab6baf9f4eba3a1b2f9f4eba3a1b2f9f4eba3baa6ebfcefbdf1a0f5c6f4c0b5fbc6baebf2fcf5eebac0b4c6f7c0b5bac2ebbab4b1f0a0f5c6f4c0b5bac2f4f8c2afbab4c6f7c0b5bac2ebbab4b1f3a0b6f1a6eff8e9e8eff3bdf3b7a0f3b1f3b7a0b6f0b1f3b8a0ade5afa4adfeaab1f3a6e0b5b4b4b4a6"}...
2024-06-15 22:49:56 | ERROR | 391 - session1 | Unknown error: cannot unpack
non-iterable NoneType object Traceback (most recent call last): File
"/root/tapswap0/bot/core/tapper.py", line 112, in login chq_result =
extract_chq(chq=chq) File "/root/tapswap0/bot/utils/scripts.py", line 132,
in extract_chq driver = web_driver(service=web_service(webdriver_path),
options=options) File
"/root/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py",
line 71, in init super().__init__(command_executor=executor,
options=options) File
"/root/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 208, in init self.start_session(capabilities) File
"/root/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 292, in start_session response = self.execute(Command.NEW_SESSION,
caps)["value"] File
"/root/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 347, in execute self.error_handler.check_response(response) File
"/root/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py",
line 229, in check_response raise exception_class(message, screen,
stacktrace) selenium.common.exceptions.TimeoutException: Message: Failed to
read marionette port


Вс, 16 июня 2024 г. в 00:02, headNbyte ***@***.***>:

**Comment by headNbyte** [comment]
@Mjstq please run these commands:
```
sudo apt purge firefox
sudo sh install.sh
```

**Comment by Mjstq** [comment]
Done it, nothing happened :(

error:
2024-06-16 10:08:46 | ERROR    | 391 - session1 | Unknown error: cannot
unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/root/tapswap0/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
  File "/root/tapswap0/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path),
options=options)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py",
line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 208, in __init__
    self.start_session(capabilities)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 347, in execute
    self.error_handler.check_response(response)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py",
line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process
unexpectedly closed with status 1

2024-06-16 10:08:49 | ERROR    | 126 - session1 | Unknown error while
getting Access Token: Message: Process unexpectedly closed with status 1
 | Response text:
{"chq":"b5fbe8f3fee9f4f2f3b5feb1f9b4e6ebfcefbdeca0ffb1f8a0feb5b4a6eaf5f4f1f8b5bcbcc6c0b4e6e9efe4e6ebfcefbdfba0edfcefeef8d4f3e9b5ecb5ade5aca4f8b4b4b2ade5acb7b5b0edfcefeef8d4f3e9b5ecb5ade5aca4fbb4b4b2ade5afb4b6b0edfcefeef8d4f3e9b5ecb5ade5acfcadb4b4b2ade5aeb6edfcefeef8d4f3e9b5ecb5ade5acfcacb4b4b2ade5a9b6b0edfcefeef8d4f3e9b5ecb5ade5acfcafb4b4b2ade5a8b7b5edfcefeef8d4f3e9b5ecb5ade5acfcaeb4b4b2ade5abb4b6edfcefeef8d4f3e9b5ecb5ade5acfca9b4b4b2ade5aab7b5edfcefeef8d4f3e9b5ecb5ade5acfca8b4b4b2ade5a5b4b6b0edfcefeef8d4f3e9b5ecb5ade5acfcabb4b4b2ade5a4b6edfcefeef8d4f3e9b5ecb5ade5acfcaab4b4b2ade5fca6f4fbb5fba0a0a0f9b4ffeff8fcf6a6f8f1eef8bdf8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0fefce9fef5b5fab4e6f8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0e0e0b5fcb1ade5aea5fcaefcb4b1b5fbe8f3fee9f4f2f3b5b4e6ebfcefbdf8a0e6e0a6f8c6baccd2d1f9dcbac0a0baaae1acade1ade1abe1acafe1a8e1a5e1aee1a9e1bab6baace1a4e1afe1acacbab1f8c6badfdadef8eabac0a0bafaf8e9d8f1f8f0f8f3e9dfe4d4f9bab1f8c6baeff6ebf2f8bac0a0bac2abd2c2a9bab1f8c6bae5f1edebeabac0a0baf4f3f3f8efd5c9d0d1bab1f8c6baccf8e5edd7bac0a0baa1f9f4eba3a1f9f4ebc1e5afadf4f9a0c1e5afafc2ebd6c2adc1e5afafbab6bac1e5afadc2eba0c1e5afafa4aba9afabc1e5afafa3a1f9f4ebc1e5afadf4f9a0bab6bac1e5afafc2e7f8c2acc1e5afafc1e5afadc2eba0c1e5afafaca4afada8c1e5afafa3a1bab6baf9f4ebc1e5afadf4f9a0c1e5afafc2d6dcc2afc1e5afafc1e5afadc2eba0c1e5afafaabab6baa4acabaec1e5afafa3a1f9f4ebc1e5afadf4f9a0c1e5afafc2faeec2aebab6bac1e5afafc1e5afadc2eba0c1e5afafa9a8a8acadc1e5afafa3a1f9f4ebc1e5afadf4f9bab6baa0c1e5afafc2abd2c2a9c1e5afafc1e5afadc2eba0c1e5afafa5aeacafaac1e5afafa3bab6baa1b2f9f4eba3a1b2f9f4eba3a1b2f9f4eba3a1b2bab6baf9f4eba3a1b2f9f4eba3a1b2f9f4eba3bab1f8c6bacdfeffd6edbac0a0bafaf8e9dce9e9eff4ffe8e9f8bab1f8c6baf4d2dcf9ccbac0a0bac2faeec2aebab1f8c6bad7c5efcccdbac0a0bac2fef5efc2baa6ebfcefbdfba0f8b1f5a0fbc6baccd2d1f9dcbac0c6baeeedf1f4e9bac0b5bae1bab4b1f4a0ade5ada6eaf5f4f1f8b5bcbcc6c0b4e6eeeaf4e9fef5b5f5c6f4b6b6c0b4e6fefceef8baadbaa7ebfcefbdf7a0fbc6badfdadef8eabac0a6fef2f3e9f4f3e8f8a6fefceef8baacbaa7f1b7a0f1a6fef2f3e9f4f3e8f8a6fefceef8baafbaa7f1b8a0ade5fefbfba9aca6fef2f3e9f4f3e8f8a6fefceef8baaebaa7ebfcefbdf6a0f2c6f7c0b5fbc6baeff6ebf2f8bac0b4c6f0c0b5bac2ebbab4a6fef2f3e9f4f3e8f8a6fefceef8baa9baa7ebfcefbdf1a0b6f3a6fef2f3e9f4f3e8f8a6fefceef8baa8baa7edc6fbc6bae5f1edebeabac0c0a0fbc6baccf8e5edd7bac0a6fef2f3e9f4f3e8f8a6fefceef8baabbaa7ebfcefbdf0a0fbc6bacdfeffd6edbac0a6fef2f3e9f4f3e8f8a6fefceef8baaabaa7e9efe4e6f8ebfcf1b5baf9f2fee8f0f8f3e9c6c1bafaf8e9d8f1f8f0f8f3e9dfe4d4f9c1bac0a6bab4a6e0fefce9fef5e6eff8e9e8eff3bdade5feadfbf8fffcfff8a6e0fef2f3e9f4f3e8f8a6fefceef8baa5baa7ebfcefbdf3a0f2c6f7c0b5fbc6baf4d2dcf9ccbac0b4c6f0c0b5bac2ebbab4a6fef2f3e9f4f3e8f8a6fefceef8baa4baa7f1b7a0b6f6a6fef2f3e9f4f3e8f8a6fefceef8baacadbaa7ebfcefbdf2a0f9f2fee8f0f8f3e9a6fef2f3e9f4f3e8f8a6fefceef8baacacbaa7eff8e9e8eff3bdf1a6fefceef8baacafbaa7ebfcefbdeda0f2c6f7c0b5fbc6bad7c5efcccdbac0b4a6fef2f3e9f4f3e8f8a6e0ffeff8fcf6a6e0e0b5b4b4b4a6fbe8f3fee9f4f2f3bdffb5feb1f9b4e6ebfcefbdf8a0fcb5b4a6eff8e9e8eff3bdffa0fbe8f3fee9f4f2f3b5fbb1fab4e6fba0fbb0ade5aca4f8a6ebfcefbdf5a0f8c6fbc0a6eff8e9e8eff3bdf5a6e0b1ffb5feb1f9b4a6e0fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbdefa0c6baa9aaabaea5a9ced0e9e4d1c8bab1baaeadafaaaca8cbfeedced5d6bab1baaca8aaaaacafadd2c9ebe9f7f6bab1baaba8facffbe4c5ebbab1baa9aeafa5cdc4e8c9ffdebab1baa9aea8a9acaafcc8dfeedacebab1baaaa9afabafadf7f2d8f9cec9bab1baaca9a4a9aba8d5f4edfcd2debab1baaca5f1eefcecc4cebab1baaea8d6ced2e4dac7bac0a6fca0fbe8f3fee9f4f2f3b5b4e6eff8e9e8eff3bdefa6e0a6eff8e9e8eff3bdfcb5b4a6e0"}...

вс, 16 июн. 2024 г. в 09:35, headNbyte ***@***.***>:

**Comment by headNbyte** [comment]
@Mjstq  Now there is another issue that I never seen before. Can you run again?

**Comment by Mjstq** [comment]
Thank you for your fast reply. Ran again:
> 2
Traceback (most recent call last):
  File "/root/tapswap0/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
  File "/root/tapswap0/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path),
options=options)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py",
line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 208, in __init__
    self.start_session(capabilities)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py",
line 347, in execute
    self.error_handler.check_response(response)
  File
"/root/tapswap0/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py",
line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process
unexpectedly closed with status 1

2024-06-16 10:13:26 | ERROR    | 126 - session1 | Unknown error while
getting Access Token: Message: Process unexpectedly closed with status 1
 | Response text:
{"chq":"b5fbe8f3fee9f4f2f3b5feb1f9b4e6ebfcefbdf2a0ffb1f8a0feb5b4a6eaf5f4f1f8b5bcbcc6c0b4e6e9efe4e6ebfcefbdfba0edfcefeef8d4f3e9b5f2b5ade5acfca4b4b4b2ade5acb6edfcefeef8d4f3e9b5f2b5ade5acfcfcb4b4b2ade5afb6edfcefeef8d4f3e9b5f2b5ade5acfcffb4b4b2ade5aeb7b5edfcefeef8d4f3e9b5f2b5ade5acfcfeb4b4b2ade5a9b4b6b0edfcefeef8d4f3e9b5f2b5ade5acfcf9b4b4b2ade5a8b7b5b0edfcefeef8d4f3e9b5f2b5ade5acfcf8b4b4b2ade5abb4b6b0edfcefeef8d4f3e9b5f2b5ade5acfcfbb4b4b2ade5aab7b5edfcefeef8d4f3e9b5f2b5ade5acffadb4b4b2ade5a5b4b6b0edfcefeef8d4f3e9b5f2b5ade5acffacb4b4b2ade5a4b6b0edfcefeef8d4f3e9b5f2b5ade5acffafb4b4b2ade5fcb7b5edfcefeef8d4f3e9b5f2b5ade5acffaeb4b4b2ade5ffb4a6f4fbb5fba0a0a0f9b4ffeff8fcf6a6f8f1eef8bdf8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0fefce9fef5b5fab4e6f8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0e0e0b5fcb1ade5aaa4aeacf9b4b1b5fbe8f3fee9f4f2f3b5b4e6ebfcefbdf8a0e6e0a6f8c6bafbdefef0ccbac0a0bafaf8e9d8f1f8f0f8f3e9dfe4d4f9bab1f8c6baf5ccedefd6bac0a0bac2fef5efc2bab1f8c6badbf5dec5d8bac0a0baf4f3f3f8efd5c9d0d1bab1f8c6bac9cecbd5d4bac0a0bac2a8c4c2acbaa6ebfcefbdfba0f8a6e9efe4e6f8ebfcf1b5baf9f2fee8f0f8f3e9c6c1bafaf8e9d8f1f8f0f8f3e9dfe4d4f9c1bac0a6bab4a6e0fefce9fef5e6eff8e9e8eff3bdade5feadfbf8fffcfff8a6e0ebfcefbdf5a0f9f2fee8f0f8f3e9b1f4a0fbc6bafbdefef0ccbac0b1f7a0bafaf8e9dce9e9eff4ffe8e9f8bab1f6a0f5c6f4c0b5fbc6baf5ccedefd6bac0b4a6f6c6fbc6badbf5dec5d8bac0c0a0baa1f9f4eba3a1f9f4ebc1e5afadf4f9a0c1e5afafc2e5aec2adc1e5afafbab6bac1e5afadc2eba0c1e5afafa5a8a9aba4c1e5afafa3a1f9f4ebc1e5afadf4f9a0bab6bac1e5afafc2a8c4c2acc1e5afafc1e5afadc2eba0c1e5afafa4afababacc1e5afafa3a1bab6baf9f4ebc1e5afadf4f9a0c1e5afafc2ebe8c2afc1e5afafc1e5afadc2eba0c1e5afafafbab6baa4aca4aac1e5afafa3a1f9f4ebc1e5afadf4f9a0c1e5afafc2f1acc2aebab6bac1e5afafc1e5afadc2eba0c1e5afafafa9a9aba9c1e5afafa3a1f9f4ebc1e5afadf4f9bab6baa0c1e5afafc2d3dfc2a9c1e5afafc1e5afadc2eba0c1e5afafa9acafaca5c1e5afafa3bab6baa1b2f9f4eba3a1b2f9f4eba3a1b2f9f4eba3a1b2bab6baf9f4eba3a1b2f9f4eba3a1b2f9f4eba3baa6ebfcefbdf1a0f5c6f4c0b5fbc6bac9cecbd5d4bac0b4c6f7c0b5bac2ebbab4b1f0a0f5c6f4c0b5fbc6bac9cecbd5d4bac0b4c6f7c0b5bac2ebbab4b1f3a0b6f1a6eff8e9e8eff3bdf3b7a0f3b1f3b7a0b6f0b1f3b8a0ade5abf8aeadfcb1f3a6e0b5b4b4b4a6fbe8f3fee9f4f2f3bdffb5feb1f9b4e6ebfcefbdf8a0fcb5b4a6eff8e9e8eff3bdffa0fbe8f3fee9f4f2f3b5fbb1fab4e6fba0fbb0ade5acfca4a6ebfcefbdf5a0f8c6fbc0a6eff8e9e8eff3bdf5a6e0b1ffb5feb1f9b4a6e0fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbdeda0c6baa4a4afaaa5abfbdedcc4ffecbab1baacafaaafacadafe9defbd4f9f5bab1baaeadaca4afdfc4d6fff6f8bab1baafadaddbcfdccfeef2bab1baaba4aaa5adeef1ffdccff2bab1baacaaa9fefaf0d5f0e9bab1baaca9add9e9dbf0d0ebbab1baaaafaeada9cac8f3edecdabab1baa8a8ada4acaaadeaf0def4daebbab1baacafa9aaa9a8a5ade5f7f6f4f2e7bab1baacace5d6dff8f6d0bac0a6fca0fbe8f3fee9f4f2f3b5b4e6eff8e9e8eff3bdeda6e0a6eff8e9e8eff3bdfcb5b4a6e0"}...


вс, 16 июн. 2024 г. в 10:12, headNbyte ***@***.***>:

**Comment by headNbyte** [comment]
@Mjstq unfortunately I don't know how to fix this issue. I need a break and will be back in 10 hours. You can share your telegram and I'll reach out to fix the issue

**Comment by Mjstq** [comment]
Thank you a lot, my telegram @mjstq

вс, 16 июн. 2024 г. в 10:20, headNbyte ***@***.***>:

**Comment by headNbyte** [comment]
@shamhi together with @Mjstq we solved the issue using Docker, some systems just have configuration issues and cannot be solves easily. So the best recommendation should be to use Docker which 100% works.

**Comment by Mjstq** [comment]
Thank you a lot for your support!

вс, 16 июн. 2024 г. в 10:54, headNbyte ***@***.***>:

**Comment by Hiradpi** [comment]
> > Does my fork solve your issues? https://github.com/headNbyte/TapSwapBot/tree/main
> > For details what is changed, please take a look at the previous two issues that I contributed to.
> 
> thanks, this work for me

well this didn't work for me same issue with the webdrivers 
im running python 3.11.9 arch linux with firefox working fine 

```Traceback (most recent call last):
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 302, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 322, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/request.py", line 81, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/request.py", line 173, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/gharch/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gharch/tool/TapSwapBot/new/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/tool/TapSwapBot/new/TapSwapBot/bot/utils/scripts.py", line 134, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 73, in __init__
    self.quit()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 86, in quit
    self.service.stop()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 146, in stop
    self.send_remote_shutdown_command()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 126, in send_remote_shutdown_command
    request.urlopen(f"{self.service_url}/shutdown")
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/gharch/.pyenv/versions/3.11.9/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
