### ISSUE TITLE
unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443

### ISSUE THREAD

**Issue by NMAP327** [shamhi/TapSwapBot#81]
2024-06-14 14:51:30 | ERROR    | 116 - coba | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ...
2024-06-14 14:51:33 | ERROR    | 381 - coba | Unknown error: cannot unpack non-iterable NoneType object
2024-06-14 14:51:57 | ERROR    | 116 - coba | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ...
2024-06-14 14:52:00 | ERROR    | 381 - coba | Unknown error: cannot unpack non-iterable NoneType object
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x000001D1A4650E50>

i got this issue, please help me to solve it.

**Comment by Mahdikhoubrouy** [comment]
same bro

**Comment by Pasha4056** [comment]
> 2024-06-14 14:51:30 | ERROR | 116 - coba | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ... 2024-06-14 14:51:33 | ERROR | 381 - coba | Unknown error: cannot unpack non-iterable NoneType object 2024-06-14 14:51:57 | ERROR | 116 - coba | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ... 2024-06-14 14:52:00 | ERROR | 381 - coba | Unknown error: cannot unpack non-iterable NoneType object Unclosed client session client_session: <aiocfscrape.CloudflareScraper object at 0x000001D1A4650E50>
> 
> i got this issue, please help me to solve it.

Use this temporarily: [](https://github.com/headNbyte/TapSwapBot)

At least everything works there

**Comment by NMAP327** [comment]
File "F:\Downloads\Exp\TapSwapBot\bot\core\tapper.py", line 96, in login
    response = await http_client.post(url='https://api.tapswap.ai/api/account/login',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 79, in _request
    resp = await super()._request(method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired]
2024-06-14 16:18:17 | ERROR    | 126 - nmap | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ...
2024-06-14 16:18:20 | ERROR    | 391 - nmap | Unknown error: cannot unpack non-iterable NoneType object


still got same issues

**Comment by Pasha4056** [comment]
> File "F:\Downloads\Exp\TapSwapBot\bot\core\tapper.py", line 96, in login response = await http_client.post(url='https://api.tapswap.ai/api/account/login', ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiocfscrape__init__.py", line 79, in _request resp = await super()._request(method, url, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\client.py", line 578, in _request conn = await self._connector.connect( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect proto = await self._create_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection raise last_exc File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection transp, proto = await self._wrap_create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\Downloads\Exp\TapSwapBot\venv\Lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] 2024-06-14 16:18:17 | ERROR | 126 - nmap | Unknown error while getting Access Token: Cannot connect to host api.tapswap.ai:443 ssl:default [The semaphore timeout period has expired] | Response text: ... 2024-06-14 16:18:20 | ERROR | 391 - nmap | Unknown error: cannot unpack non-iterable NoneType object
> 
> still got same issues

Try not to use a proxy, and check if you have all the packages from requirements.txt installed, you need to do this from the venv in which you run the bot

**Comment by Dumpff** [comment]
I have this error :(. 
1. I launch install.bat (waiting until installation complete)
2. I launch start.bat (And have error)
```Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "D:\TapSwapBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\TapSwapBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\TapSwapBot-main\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "D:\TapSwapBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "D:\TapSwapBot-main\bot\config\config.py", line 31, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "D:\TapSwapBot-main\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "D:\TapSwapBot-main\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing```

**Comment by YavorCool** [comment]
I guess there is some problem with http client and ssl
I use other soft for blum and iceberg, it works fine, they use another proxyconnector
I tried to set trust_env=True in the ClientSession and verify_ssl=False in proxy connector, but it didn't help
Maybe the solution can be found somewhere here at 57 row https://github.com/Axcent-ape/IcebergAppBot/blob/main/utils/iceberg.py

**Comment by YavorCool** [comment]
yes it works like this, but it doesn't use proxy, problem is inside ProxyConnector
![image](https://github.com/shamhi/TapSwapBot/assets/13070666/a8e84491-c01e-407f-92c5-39a9828c38fb)
