### ISSUE TITLE
error Webdriver

### ISSUE THREAD

**Issue by Dxwny** [shamhi/TapSwapBot#88]
```
Traceback (most recent call last):
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\bot\core\tapper.py", line 17, in <module>
    from bot.utils.scripts import extract_chq, escape_html
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\bot\utils\scripts.py", line 53, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\venv\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\venv\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\venv\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\GitHub Repositories\TapSwap-Rab\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
what could be the cause this error?

**Comment by aaero-13** [comment]
# Linux
~/TapSwapBot >>> python3 -m venv venv
~/TapSwapBot >>> source venv/bin/activate
~/TapSwapBot >>> pip3 install -r requirements.txt
~/TapSwapBot >>> cp .env-example .env
~/TapSwapBot >>> nano .env  # Здесь вы обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию
~/TapSwapBot >>> sh install.sh
~/TapSwapBot >>> python3 main.py

# Windows
~/TapSwapBot >>> python -m venv venv
~/TapSwapBot >>> venv\Scripts\activate
~/TapSwapBot >>> pip install -r requirements.txt
~/TapSwapBot >>> copy .env-example .env
~/TapSwapBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию
~/TapSwapBot >>> python main.py

**Comment by Dxwny** [comment]
> # Linux
> ~/TapSwapBot >>> python3 -m venv venv ~/TapSwapBot >>> source venv/bin/activate ~/TapSwapBot >>> pip3 install -r requirements.txt ~/TapSwapBot >>> cp .env-example .env ~/TapSwapBot >>> nano .env # Здесь вы обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию ~/TapSwapBot >>> sh install.sh ~/TapSwapBot >>> python3 main.py
> 
> # Windows
> ~/TapSwapBot >>> python -m venv venv ~/TapSwapBot >>> venv\Scripts\activate ~/TapSwapBot >>> pip install -r requirements.txt ~/TapSwapBot >>> copy .env-example .env ~/TapSwapBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию ~/TapSwapBot >>> python main.py

I saw this perfectly well, moreover, just in case, I re-created venv and installed all the modules there - it doesn't work, is there something else to essentially say?

**Comment by whatever193** [comment]
> > # Linux
> > ~/TapSwapBot >>> python3 -m venv venv ~/TapSwapBot >>> source venv/bin/activate ~/TapSwapBot >>> pip3 install -r requirements.txt ~/TapSwapBot >>> cp .env-example .env ~/TapSwapBot >>> nano .env # Здесь вы обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию ~/TapSwapBot >>> sh install.sh ~/TapSwapBot >>> python3 main.py
> > # Windows
> > ~/TapSwapBot >>> python -m venv venv ~/TapSwapBot >>> venv\Scripts\activate ~/TapSwapBot >>> pip install -r requirements.txt ~/TapSwapBot >>> copy .env-example .env ~/TapSwapBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию ~/TapSwapBot >>> python main.py
> 
> I saw this perfectly well, moreover, just in case, I re-created venv and installed all the modules there - it doesn't work, is there something else to essentially say?

did you forget install chrome?

**Comment by Dxwny** [comment]
> > > # Linux
> > > ~/TapSwapBot >>> python3 -m venv venv ~/TapSwapBot >>> source venv/bin/activate ~/TapSwapBot >>> pip3 install -r requirements.txt ~/TapSwapBot >>> cp .env-example .env ~/TapSwapBot >>> nano .env # Здесь вы обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию ~/TapSwapBot >>> sh install.sh ~/TapSwapBot >>> python3 main.py
> > > # Windows
> > > ~/TapSwapBot >>> python -m venv venv ~/TapSwapBot >>> venv\Scripts\activate ~/TapSwapBot >>> pip install -r requirements.txt ~/TapSwapBot >>> copy .env-example .env ~/TapSwapBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию ~/TapSwapBot >>> python main.py
> > 
> > 
> > I saw this perfectly well, moreover, just in case, I re-created venv and installed all the modules there - it doesn't work, is there something else to essentially say?
> 
> did you forget install chrome?

do I need to install chrome?

**Comment by kamranmt21** [comment]
> > > > # Linux
> > > > ~/TapSwapBot >>> python3 -m venv venv ~/TapSwapBot >>> source venv/bin/activate ~/TapSwapBot >>> pip3 install -r requirements.txt ~/TapSwapBot >>> cp .env-example .env ~/TapSwapBot >>> nano .env # Здесь вы обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию ~/TapSwapBot >>> sh install.sh ~/TapSwapBot >>> python3 main.py
> > > > # Windows
> > > > ~/TapSwapBot >>> python -m venv venv ~/TapSwapBot >>> venv\Scripts\activate ~/TapSwapBot >>> pip install -r requirements.txt ~/TapSwapBot >>> copy .env-example .env ~/TapSwapBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию ~/TapSwapBot >>> python main.py
> > > 
> > > 
> > > I saw this perfectly well, moreover, just in case, I re-created venv and installed all the modules there - it doesn't work, is there something else to essentially say?
> > 
> > 
> > did you forget install chrome?
> 
> do I need to install chrome?

Yes, as the script `TapSwapBot` is using some kind of web-scraping, you need to install a webbrowser **in your terminal**.
as the README said, run this command:

```
cd TapSwapBot
sh install.sh
```
