### ISSUE TITLE
Problem with webdriver in Termux in last update

### ISSUE THREAD

**Issue by kamranmt21** [shamhi/TapSwapBot#91]
I don't know how can I figure it out..

```
[Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/TapSwapBot/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 62, in __init__
    self.service.start()
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'webdriver/geckodriver'
2024-06-16 22:24:20 | ERROR    | 126 - 2819 | Unknown error while getting Access Token: [Errno 8] Exec format error: 'webdriver/geckodriver' | Response text: {"chq":"b5fbe8f3fee9f4f2f3b5feb1f9b4e6ebfcefbdeca0ffb1f8a0feb5b4a6eaf5f4f1f8b5bcbcc6c0b4e6e9efe4e6ebfcefbdfba0edfcefeef8d4f3e9b5ecb5ade5acfbaeb4b4b2ade5acb6b0edfcefeef8d4f3e9b5ecb5ade5acfba9b4b4b2ade5afb7b5b0edfcefeef8d4f3e9b5ecb5ade5acfba8b4b4b2ade5aeb4b6b0edfcefeef8d4f3e9b5ecb5ade5acfbabb4b4b2ade5a9b7b5edfcefeef8d4f3e9b5ecb5ade5acfbaab4b4b2ade5a8b4b6b0edfcefeef8d4f3e9b5ecb5ade5acfba5b4b4b2ade5abb7b5edfcefeef8d4f3e9b5ecb5ade5acfba4b4b4b2ade5aab4b6b0edfcefeef8d4f3e9b5ecb5ade5acfbfcb4b4b2ade5a5b6edfcefeef8d4f3e9b5ecb5ade5acfbffb4b4b2ade5a4b7b5b0edfcefeef8d4f3e9b5ecb5ade5acfbfeb4b4b2ade5fcb4b6b0edfcefeef8d4f3e9b5ecb5ade5acfbf9b4b4b2ade5ffb7b5b0edfcefeef8d4f3e9b5ecb5ade5acfbf8b4b4b2ade5feb4a6f4fbb5fba0a0a0f9b4ffeff8fcf6a6f8f1eef8bdf8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0fefce9fef5b5fab4e6f8c6baede8eef5bac0b5f8c6baeef5f4fbe9bac0b5b4b4a6e0e0e0b5fcb1ade5fcaff8aef8b4b1b5fbe8f3fee9f4f2f3b5b4e6ebfcefbdf8a0e6e0a6f8c6bac9facbf7e5bac0a0baa4e1ace1acade1acafe1aae1aee1ade1abe1a8e1bab6baacace1a5e1afe1a9bab1f8c6baead9eee9c7bac0a0bac2deafc2adbab1f8c6baf2e9dae8eabac0a0baf4f3f3f8efd5c9d0d1bab1f8c6bad2d0fbfef9bac0a0baa1f9f4eba3a1f9f4ebc1e5afadf4f9a0c1e5afafc2deafc2adc1e5afafbab6bac1e5afadc2eba0c1e5afafa8afacaeafc1e5afafa3a1f9f4ebc1e5afadf4f9a0bab6bac1e5afafc2d1e8c2acc1e5afafc1e5afadc2eba0c1e5afafafadaaafa5c1e5afafa3a1bab6baf9f4ebc1e5afadf4f9a0c1e5afafc2efcbc2afc1e5afafc1e5afadc2eba0c1e5afafafbab6baa8adaaaec1e5afafa3a1f9f4ebc1e5afadf4f9a0c1e5afafc2c9d4c2aebab6bac1e5afafc1e5afadc2eba0c1e5afafaeafaea9aec1e5afafa3a1f9f4ebc1e5afadf4f9bab6baa0c1e5afafc2c9f2c2a9c1e5afafc1e5afadc2eba0c1e5afafa5afadaea8c1e5afafa3bab6baa1b2f9f4eba3a1b2f9f4eba3a1b2f9f4eba3a1b2bab6baf9f4eba3a1b2f9f4eba3a1b2f9f4eba3bab1f8c6bad2cbeff8dabac0a0bac2c9f2c2a9bab1f8c6badad5e4ccd4bac0a0bafaf8e9d8f1f8f0f8f3e9dfe4d4f9baa6ebfcefbdfba0f8b1f5a0fbc6bac9facbf7e5bac0c6baeeedf1f4e9bac0b5bae1bab4b1f4a0ade5ada6eaf5f4f1f8b5bcbcc6c0b4e6eeeaf4e9fef5b5f5c6f4b6b6c0b4e6fefceef8baadbaa7ebfcefbdf7a0f6c6f2c0b5fbc6baead9eee9c7bac0b4c6edc0b5bac2ebbab4a6fef2f3e9f4f3e8f8a6fefceef8baacbaa7ebfcefbdf6a0f9f2fee8f0f8f3e9a6fef2f3e9f4f3e8f8a6fefceef8baafbaa7f1b8a0ade5a5a9a4fcffa6fef2f3e9f4f3e8f8a6fefceef8baaebaa7f3c6fbc6baf2e9dae8eabac0c0a0fbc6bad2d0fbfef9bac0a6fef2f3e9f4f3e8f8a6fefceef8baa9baa7eff8e9e8eff3bdf1a6fefceef8baa8baa7ebfcefbdf1a0b6f7a6fef2f3e9f4f3e8f8a6fefceef8baabbaa7ebfcefbdf0a0f6c6f2c0b5fbc6bad2cbeff8dabac0b4c6edc0b5bac2ebbab4a6fef2f3e9f4f3e8f8a6fefceef8baaabaa7ebfcefbdf3a0f6c6f2c0b5bac2fef5efc2bab4a6fef2f3e9f4f3e8f8a6fefceef8baa5baa7f1b7a0b6f0a6fef2f3e9f4f3e8f8a6fefceef8baa4baa7e9efe4e6f8ebfcf1b5baf9f2fee8f0f8f3e9c6c1bafaf8e9d8f1f8f0f8f3e9dfe4d4f9c1bac0a6bab4a6e0fefce9fef5e6eff8e9e8eff3bdade5feadfbf8fffcfff8a6e0fef2f3e9f4f3e8f8a6fefceef8baacadbaa7ebfcefbdf2a0fbc6badad5e4ccd4bac0a6fef2f3e9f4f3e8f8a6fefceef8baacacbaa7f1b7a0f1a6fef2f3e9f4f3e8f8a6fefceef8baacafbaa7ebfcefbdeda0bafaf8e9dce9e9eff4ffe8e9f8baa6fef2f3e9f4f3e8f8a6e0ffeff8fcf6a6e0e0b5b4b4b4a6fbe8f3fee9f4f2f3bdffb5feb1f9b4e6ebfcefbdf8a0fcb5b4a6eff8e9e8eff3bdffa0fbe8f3fee9f4f2f3b5fbb1fab4e6fba0fbb0ade5acfbaea6ebfcefbdf5a0f8c6fbc0a6eff8e9e8eff3bdf5a6e0b1ffb5feb1f9b4a6e0fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbdefa0c6baafafaea9aaa8a9faf8cadfd0fabab1baaca9dbf1ffd9d8eebab1baacadafaea9aeafa5c4f1ecf6cbdfbab1baa4eed9ceffe5d5bab1baa8a8aeaba4acadd6cfded7d5d9bab1baacacd4fad2cad2d7bab1baaeaeaeaba4abacafc8d1e9d0dbe5bab1baaeafaaa4adaffaf0d2eaf5dabab1baafa5afaca9f4f8cccaf5d3bab1baafaba9eadafaced1ecbab1baafaeafabaeabcbd2faccebe9bab1baa4a8dbf1f0e4e5c4bac0a6fca0fbe8f3fee9f4f2f3b5b4e6eff8e9e8eff3bdefa6e0a6eff8e9e8eff3bdfcb5b4a6e0"}...]
```

**Comment by MoeinNS** [comment]
same

**Comment by kamranmt21** [comment]
With the last update, it is working fine for me.

**Comment by celepok** [comment]
Same
