### ISSUE TITLE
describing the main problem

### ISSUE THREAD

**Issue by MoeinNS** [shamhi/TapSwapBot#92]
## A but I wanna run the script as a service , I used this service content 

```
 [Unit]
Description=TapSwapBotService
After=network.target

[Service]
User=root
WorkingDirectory=/root/TapSwapBot/
Environment=PATH=/root/TapSwapBot/venv/bin/
ExecStart=/root/TapSwapBot/venv/bin/python3 /root/TapSwapBot/main.py -a 2

Restart=always

[Install]
WantedBy=multi-user.target
```
``

## A but a few days ago I've got this error like other guys

```
[Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/TapSwapBot/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 62, in __init__
    self.service.start()
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/data/data/com.termux/files/home/TapSwapBot/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 208, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'webdriver/geckodriver'
```

**Comment by kamranmt21** [comment]
Your problem is related to my issue #91. I think it is a problem with the webdriver.

**Comment by kamranmt21** [comment]
@MoeinNS 
with the last update, it is working fine for me now. I'm using Termux, just in case.
(If your problem solved, don't forget to close this issue)
