### ISSUE TITLE
Again Error 

### ISSUE THREAD

**Issue by Pawansingh333** [shamhi/TapSwapBot#97]
2024-06-18 23:04:18 | ERROR    | 391 - 918402865691 | Unknown error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\Crypto_Mining\TapSwapBot-main\bot\core\tapper.py", line 99, in login
    response.raise_for_status()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-18 23:04:22 | ERROR    | 126 - 918402865691 | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_init_data"}...
2024-06-18 23:04:25 | ERROR    | 391 - 918402865691 | Unknown error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\Crypto_Mining\TapSwapBot-main\bot\core\tapper.py", line 99, in login
    response.raise_for_status()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-18 23:04:28 | ERROR    | 126 - 918402865691 | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_init_data"}...

**Comment by kamranmt21** [comment]
@Pawansingh333 Check the last update. with the last update, it has started working for me (I'm using Termux. just in case).
