### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Glo\Desktop\tapWORK\TapSwapBot-main (3)\TapSwapBot-main\bot\core\tapper.py", line 99, in login     response.raise_for_status()   File "C:\Users\Glo\Desktop\tapWORK\TapSwapBot-main (3)\TapSwapBot-main\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status     raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') 2024-06-19 22:15:08 | ERROR    | 126 - work | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_request[1]"}... 2024-06-19 22:15:11 | ERROR    | 391 - work | Unknown error: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by faerhjio0gase** [shamhi/TapSwapBot#99]
Traceback (most recent call last):
  File "C:\Users\Glo\Desktop\tapWORK\TapSwapBot-main (3)\TapSwapBot-main\bot\core\tapper.py", line 99, in login
    response.raise_for_status()
  File "C:\Users\Glo\Desktop\tapWORK\TapSwapBot-main (3)\TapSwapBot-main\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login')
2024-06-19 22:15:08 | ERROR    | 126 - work | Unknown error while getting Access Token: 400, message='Bad Request', url=URL('https://api.tapswap.ai/api/account/login') | Response text: {"statusCode":400,"message":"invalid_request[1]"}...
2024-06-19 22:15:11 | ERROR    | 391 - work | Unknown error: cannot unpack non-iterable NoneType object
![Снимок экрана 2024-06-19 221620](https://github.com/shamhi/TapSwapBot/assets/172613518/e3e4698c-6261-447b-a42a-b64d274853e1)

**Comment by bayyesterday** [comment]
same

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/TapSwapBot/issues/112
